In [1]:

# 2022-out-7: Excelente espectro para testes, tenho usado ultimamente:
# a_pattern = 'Si/SI2018/SI11318.Chn'
# 2022-nov-16: outros espectros:
# a_pattern = "Filtros/2022/Cci/CCI1603-I.Chn"
# a_pattern = "Filtros/2022/Cci/CCI2302-I.Chn"

# a_pattern = "Eso_non_existe.Chn"

# 2022-Dez-21 Buscando outro espectro
# a_pattern = 'CCI1603-I'
# 2022-Dez-28 Este é um espectro mais recente:
# a_pattern = 'SI09722.Chn'
# 2022-Dez-28 Este é um espectro mais recente que posso comparar com saída do Genie:
# a_pattern = 'SI06322.Chn'
# a_pattern = 'SI06122.Chn'

In [2]:
import numpy as np
from numpy.polynomial import Polynomial as P  # 2020-09-06 Esta é a nova classe recomendada
from sklearn import linear_model

import pandas as pd
from random import randrange
# import plotly.graph_objects as go

In [3]:
from ograyspy_class import Ograyspy, select_spectrum_from_folder_list
from spec_class import Spec

In [4]:
ogra = Ograyspy()
print(ogra.info_node)
to_be_found = 'Genie_Transfer'
# to_be_found = 'some_spectra' # NAO ESTAH ACHANDO localmente no note!

Found folder name:  C:\Users\mmaduar\.atom
Parts:  ('C:\\', 'Users', 'mmaduar', '.atom')
No. spec files:  0
I56611


In [5]:
print('\nExec ogra.define_files_folder(to_be_found):')
ogra.define_files_folder(to_be_found)
print(ogra.pkl_folder_files)
spectra_list_df = pd.read_pickle(ogra.pkl_folder_files)
del ogra


Exec ogra.define_files_folder(to_be_found):
Found folder name:  C:\Users\mmaduar\Nextcloud\Genie_Transfer
Parts:  ('C:\\', 'Users', 'mmaduar', 'Nextcloud', 'Genie_Transfer')
No. spec files:  7317
WindowsI56611.pkl


In [6]:
reduc_nms = spectra_list_df.reduced_names_files_list[0]
fil_lst = spectra_list_df.files_list[0]
spc_pth = spectra_list_df.spectra_path[0]

In [7]:
len(reduc_nms)

7317

In [8]:
# 2022-Dez-28 Esse é um espectro mais recente que posso comparar com saída do Genie:
a_pattern = 'SI06122.Chn'

In [9]:
f_name, reduced_f_name = select_spectrum_from_folder_list(reduc_nms, fil_lst, spc_pth, a_pattern)
f_name, reduced_f_name

Existing:
Achou! indice=1016, nomearq = almera22/user2023/SI2022/SI06122.Chn
Final choices:
spectra_path: C:\Users\mmaduar\Nextcloud\Genie_Transfer
a_spec_name: C:\Users\mmaduar\Nextcloud\Genie_Transfer\almera22\user2023\SI2022\SI06122.Chn
reduced_f_name: almera22/user2023/SI2022/SI06122.Chn


(WindowsPath('C:/Users/mmaduar/Nextcloud/Genie_Transfer/almera22/user2023/SI2022/SI06122.Chn'),
 'almera22/user2023/SI2022/SI06122.Chn')

In [10]:
a_spec = Spec(f_name, reduced_f_name)

In [11]:
vars (a_spec)

{'net_spec_ser_an': None,
 'final_composed_baseline': None,
 'f_name': WindowsPath('C:/Users/mmaduar/Nextcloud/Genie_Transfer/almera22/user2023/SI2022/SI06122.Chn'),
 'reduced_f_name': 'almera22/user2023/SI2022/SI06122.Chn',
 'sufx': '.chn',
 'spec_io': None,
 'lv_time': 50000.0,
 'rl_time': 50028.96,
 'source_datetime': None,
 'results_pkl_file': WindowsPath('.'),
 'origin_spec_ser_an': <generic_series_analysis_class.GenericSeriesAnalysis at 0x1716f369ac0>,
 'start_datetime': datetime.datetime(2022, 7, 27, 16, 56, 29),
 'det_descr': 'MAQUINA_01 MCB 1 Input 1',
 'sam_descr': 'SI-061/22 Agua da Piscina Reator IEA-R1 (GMX)',
 'channel_energy_calib': <genericcalib_class.ChannelEnergyCalib at 0x1716fca9670>,
 'nucl_an': <nuclide_analysis_class.NuclideAnalysis at 0x1716fca9700>}

In [12]:
# 2024-Feb-15: Reactivate to analyze with rough sums
# a_spec.total_analysis(gener_dataframe=True, results_path='../ograyspy_results')
# A opção acima, gener_dataframe=True,  grava o pkl_file do espectro
# vars(a_spec)

In [13]:
# 2024-Feb-15:
# Testing lmfit
a_spec.total_analysis(peak_area_calc_method='gaussian_with_tail')
# A opção acima, gener_dataframe=True,  grava o pkl_file do espectro
vars(a_spec)

Starting Spec.total_analysis...
resolve_peaks_and_regions:
define_multiplets_regions completado. Define: self.mix_regions.
resolve_peaks_and_regions:
define_multiplets_regions completado. Define: self.mix_regions.
[27. 28. 29. 30. 31. 32. 33.]
[  0.           0.         617.18064592 818.64619493 367.80951529
  90.30601139   0.        ]
[125. 126. 127. 128. 129. 130. 131. 132.]
[447.4263586  294.98162556 361.32940596 720.58562658 649.04632671
 261.66474176 113.72218635  28.03222329]
[141. 142. 143. 144. 145. 146. 147. 148.]
[ 12.61479812   0.         165.99750047 385.29459126 389.571554
 142.5529984   54.78173023 127.79480442]
[231. 232. 233. 234. 235. 236. 237. 238. 239.]
[ 49.47592158  24.27568087   0.          75.8739986   82.65604544
 123.42578363  39.22073955  33.01749672  34.81365348]
[392. 393. 394. 395. 396. 397. 398. 399. 400. 401.]
[  0.          45.63037121  52.22731586  91.93540318 162.84530219
 113.60603604  85.27902567  28.7823765   18.25062964  31.75398046]
[487. 488. 489

{'net_spec_ser_an': <generic_series_analysis_class.GenericSeriesAnalysis at 0x1716fca9a60>,
 'final_composed_baseline': <generic_series_analysis_class.GenericSeriesAnalysis at 0x1715f001400>,
 'f_name': WindowsPath('C:/Users/mmaduar/Nextcloud/Genie_Transfer/almera22/user2023/SI2022/SI06122.Chn'),
 'reduced_f_name': 'almera22/user2023/SI2022/SI06122.Chn',
 'sufx': '.chn',
 'spec_io': None,
 'lv_time': 50000.0,
 'rl_time': 50028.96,
 'source_datetime': None,
 'results_pkl_file': WindowsPath('.'),
 'origin_spec_ser_an': <generic_series_analysis_class.GenericSeriesAnalysis at 0x1716f369ac0>,
 'start_datetime': datetime.datetime(2022, 7, 27, 16, 56, 29),
 'det_descr': 'MAQUINA_01 MCB 1 Input 1',
 'sam_descr': 'SI-061/22 Agua da Piscina Reator IEA-R1 (GMX)',
 'channel_energy_calib': <genericcalib_class.ChannelEnergyCalib at 0x1716fca9670>,
 'nucl_an': <nuclide_analysis_class.NuclideAnalysis at 0x1716fca9700>}

In [14]:
# The End