In [1]:
# AQUI: Compatibilizar as séries plotadas acima, estão incoerentes.

In [2]:
import numpy as np

In [3]:
counts = np.array([14,17,35,12,9])

In [4]:
cts_cumsum = np.cumsum(counts[1:])
cts_cumsum.resize(5)
cts_cumsum = np.roll(cts_cumsum,1)
cts_cumsum

array([ 0, 17, 52, 64, 73])

In [5]:
coeff = (counts[-1] - counts[0]) / cts_cumsum[-1]
coeff

-0.0684931506849315

In [6]:
step_cts = cts_cumsum * coeff + counts[0]
step_cts

array([14.        , 12.83561644, 10.43835616,  9.61643836,  9.        ])

In [7]:
np.concatenate([[2],[1,4,3],[6,5]])

array([2, 1, 4, 3, 6, 5])

In [8]:
# Fazer a superposićão de arrays com índices e valores dados por coordenadas

In [9]:
dir()

['In',
 'Out',
 '_',
 '_4',
 '_5',
 '_6',
 '_7',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'coeff',
 'counts',
 'cts_cumsum',
 'exit',
 'get_ipython',
 'np',
 'quit',
 'step_cts']

In [10]:
step_cts

array([14.        , 12.83561644, 10.43835616,  9.61643836,  9.        ])

In [11]:
indices = np.array([1,3,4])
valores = np.array([137,229,439])

In [12]:
step_cts[indices] = valores

In [13]:
step_cts

array([ 14.        , 137.        ,  10.43835616, 229.        ,
       439.        ])

In [18]:
testes_nz = np.where(step_cts<100, step_cts, 13)
testes_nz

array([14.        , 13.        , 10.43835616, 13.        , 13.        ])