In [1]:
import sys
import os
sys.executable

'/home/marcelofm/ogrsp_in_github/venv/bin/python'

In [2]:
src_dir = os.path.abspath(sys.path[0] + '/../src')
spectra_dir = sys.path[0] + '/../data/some_spectra'
home_path = os.path.expanduser('~')

In [3]:
print(src_dir)

/home/marcelofm/ogrsp_in_github/src


In [4]:
sys.path.insert(0, src_dir)
print(sys.path)

['/home/marcelofm/ogrsp_in_github/src', '/home/marcelofm/ogrsp_in_github/tests', '/home/marcelofm/Nextcloud/Python_Scripts', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/home/marcelofm/ogrsp_in_github/venv/lib/python3.10/site-packages']


In [5]:
!{sys.executable} -m pip install --upgrade pip

In [6]:
!{sys.executable} -m pip install scipy

In [7]:
!{sys.executable} -m pip install pandas ipywidgets plotly

In [8]:
import scipy
from unittest import TestCase

In [9]:
from spec_class import Spec
from spec_graphics_class import GenericGraphics
from spec_graphics_class import CountsGraphic, PeaksAndRegionsGraphic, BaselineGraphic


In [10]:
class TestSpec(TestCase):
    def setUp(self):
        self.spec = Spec(spectra_dir + '/' + 'CCI0202-I.Chn')

    def test_file_exists(self):
        self.assertGreater(self.spec.gross_spec_ser_an.n_ch, 0)

    def test_graphics(self):
        from spec_graphics_class import GenericGraphics
        self.assertTrue(True)

    def test_plot(self):
        from spec_graphics_class import CountsGraphic
        print(self.spec.f_name)
        self.home_path = os.path.expanduser('~')
        spec_graphic = CountsGraphic(self.spec.f_name,
                                     self.spec.gross_spec_ser_an,
                                     self.home_path,
                                     'test_plot')
        del spec_graphic

    def test_fft_plot(self):
        from scipy.fft import fft, ifft, fftfreq, fftshift
        from spec_graphics_class import GenericGraphics
        # fft_graphic = GenericGraphics('Qquer_coisa', [1,2,3], [4,5,6])
        # Number of sample points
        # N = 600
        # sample spacing
        # T = 1.0 / 800.0
        # x = np.linspace(0.0, N * T, N, endpoint=False)
        # y = np.sin(50.0 * 2.0 * np.pi * x) + 0.5 * np.sin(80.0 * 2.0 * np.pi * x)
        # yf = fft(y)
        # xf = fftfreq(N, T)[:N // 2]
        # fft_ys = 2.0 / N * np.abs(yf[0:N // 2])
        xf = self.spec.gross_spec_ser_an.x_s
        fft_ys = fft(self.spec.gross_spec_ser_an.y_s)
        fft_ys[2000:2096] = 0.0
        fft_ys[1800:2296] = 0.0
        ifft_ys = ifft(fft_ys)
        ys_plot = abs(ifft_ys)
        fft_graphic = GenericGraphics('Qquer_coisa', xf, ys_plot)

In [11]:
test_spec = TestSpec()
test_spec.setUp()

In [12]:
vars(test_spec.spec)

{'net_spec_ser_an': None,
 'final_composed_baseline': None,
 'f_name': '/home/marcelofm/ogrsp_in_github/tests/../data/some_spectra/CCI0202-I.Chn',
 'sufx': '.chn',
 'spec_io': None,
 'pkl_file': PosixPath('/home/marcelofm/ogrsp_in_github/tests/../data/some_spectra/CCI0202-I.xz'),
 'spec_pks_df': Empty DataFrame
 Columns: []
 Index: [],
 'gross_spec_ser_an': <generic_series_analysis_class.GenericSeriesAnalysis at 0x7f44332846d0>}

In [13]:
test_spec.test_file_exists()

In [14]:
test_spec.test_plot()

/home/marcelofm/ogrsp_in_github/tests/../data/some_spectra/CCI0202-I.Chn


In [15]:
test_spec.spec.total_analysis()

k_sep_pk:  2.0
smoo:  3000.0
widths_range:  (4.0, 20.0)
Exec peaks_search(gross=True), espectro ORIGINAL
resolve_peaks_and_regions:
define_multiplets_regions completado. Define: self.mix_regions.
resolve_peaks_and_regions:
define_multiplets_regions completado. Define: self.mix_regions.


In [16]:
vars(test_spec.spec.gross_spec_ser_an)

{'mix_regions': array([[  31,   46],
        [  47,   65],
        [  90,  109],
        [ 127,  138],
        [ 143,  156],
        [ 174,  191],
        [ 229,  259],
        [ 265,  276],
        [ 295,  357],
        [ 402,  432],
        [ 433,  478],
        [ 488,  516],
        [ 517,  522],
        [ 544,  557],
        [ 562,  569],
        [ 573,  588],
        [ 608,  639],
        [ 674,  695],
        [ 721,  738],
        [ 746,  759],
        [ 796,  807],
        [ 836,  857],
        [ 867,  901],
        [ 927,  942],
        [ 951,  978],
        [1000, 1017],
        [1023, 1040],
        [1084, 1099],
        [1123, 1156],
        [1182, 1213],
        [1288, 1297],
        [1308, 1319],
        [1363, 1373],
        [1376, 1387],
        [1393, 1406],
        [1426, 1443],
        [1474, 1491],
        [1497, 1508],
        [1531, 1548],
        [1590, 1603],
        [1605, 1622],
        [1663, 1670],
        [1692, 1701],
        [1741, 1762],
        [1791, 18

In [17]:
vars(test_spec.spec.gross_spec_ser_an.pk_parms)

{'peaks': array([  38,   54,   60,   99,  132,  149,  177,  183,  237,  244,  253,
         270,  301,  315,  318,  335,  348,  408,  416,  426,  440,  454,
         468,  491,  505,  519,  550,  565,  577,  582,  613,  623,  684,
         729,  752,  801,  846,  875,  891,  934,  964, 1007, 1012, 1031,
        1091, 1136, 1148, 1190, 1196, 1200, 1292, 1313, 1366, 1369, 1381,
        1399, 1434, 1482, 1502, 1539, 1596, 1613, 1666, 1696, 1751, 1799,
        1831, 1843, 1871, 1892, 1923, 1942, 2043, 2181, 2231, 2266, 2401,
        2672, 2897, 2969]),
 'pk_hei': array([], dtype=float64),
 'widths': (None, None),
 'mix_regions': array([], dtype=float64),
 'plateaux': array([], dtype=float64),
 'fwhm_plateaux': array([], dtype=float64),
 'wide_regions': array([], dtype=float64),
 'propts': {'peak_heights': array([1.1900e+03, 1.9825e+04, 5.2850e+03, 4.5900e+02, 3.7700e+02,
         2.9800e+02, 6.0200e+02, 6.4700e+02, 3.7400e+02, 3.6300e+02,
         4.6700e+03, 3.0242e+04, 1.3060e+03, 7.1200

In [18]:
gross_counts_graphics = CountsGraphic('Contagens brutas',
                                      test_spec.spec.gross_spec_ser_an,
                                      home_path,
                                      'gross_counts')
del gross_counts_graphics

In [19]:
peaks_and_regions_graphic = PeaksAndRegionsGraphic(
    'Picos e regiões',
    test_spec.spec.gross_spec_ser_an,
    home_path,
    'gross_peaks'
)
del peaks_and_regions_graphic

In [20]:
base_line_graphic = BaselineGraphic(
    'Nome para título da figura',
    test_spec.spec.gross_spec_ser_an,
    home_path)
del base_line_graphic

In [21]:
net_counts_graphics = CountsGraphic('Contagens líquidas',
                                    test_spec.spec.net_spec_ser_an,
                                    home_path,
                                    'net_counts')
del net_counts_graphics

In [22]:
net_peaks_graphic = PeaksAndRegionsGraphic(
    'Picos líquidos',
    test_spec.spec.net_spec_ser_an,
    home_path,
    'net_peaks'
)
del net_peaks_graphic

In [23]:
test_spec.spec.gross_spec_ser_an.chans_in_multiplets_list

[array([31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
        44., 45.]),
 array([47., 48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.,
        60., 61., 62., 63., 64.]),
 array([ 90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.,
        101., 102., 103., 104., 105., 106., 107., 108.]),
 array([127., 128., 129., 130., 131., 132., 133., 134., 135., 136., 137.]),
 array([143., 144., 145., 146., 147., 148., 149., 150., 151., 152., 153.,
        154., 155.]),
 array([174., 175., 176., 177., 178., 179., 180., 181., 182., 183., 184.,
        185., 186., 187., 188., 189., 190.]),
 array([229., 230., 231., 232., 233., 234., 235., 236., 237., 238., 239.,
        240., 241., 242., 243., 244., 245., 246., 247., 248., 249., 250.,
        251., 252., 253., 254., 255., 256., 257., 258.]),
 array([265., 266., 267., 268., 269., 270., 271., 272., 273., 274., 275.]),
 array([295., 296., 297., 298., 299., 300., 301., 302., 303., 304., 305.,
        306., 307.,

In [24]:
test_spec.spec.gross_spec_ser_an.calculated_step_counts

[array([390.18507446, 390.70341171, 392.35308517, 395.78780124,
        401.55585415, 410.03701383, 421.19007725, 434.11828827,
        446.27184417, 455.82994236, 462.38915904, 466.96344921,
        471.52019227, 471.52019227, 477.32916305]),
 array([487.6536149 , 487.08548427, 486.13907639, 484.55111832,
        482.41881598, 479.12604985, 469.78374578, 451.82480373,
        434.27316581, 421.73798426, 414.85087829, 411.65652424,
        408.41666718, 403.47895788, 398.96575187, 395.50874958,
        395.50874958, 395.13487679]),
 array([277.05627524, 275.81069106, 274.53128587, 273.2020172 ,
        271.80337075, 270.31598375, 268.73513811, 267.07438374,
        265.36553853, 263.65289788, 261.9700727 , 260.33419896,
        258.74874199, 257.21471392, 255.733478  , 254.30674859,
        252.9365912 , 252.9365912 , 251.81179276]),
 array([181.88042479, 183.92463754, 186.18307666, 188.70258034,
        191.47074381, 194.40252001, 197.3402196 , 200.08503309,
        202.52311957, 202.

In [25]:
graph_test = GenericGraphics(test_spec.spec.f_name,
                             home_path,
                             'steps_graph',
                             test_spec.spec.gross_spec_ser_an.x_s,
                             test_spec.spec.gross_spec_ser_an.eval_baseline,
                             test_spec.spec.gross_spec_ser_an.chans_in_multiplets_list,
                             test_spec.spec.gross_spec_ser_an.calculated_step_counts)

In [26]:
test_spec.spec.gross_spec_ser_an.chans_in_multiplets_list

[array([31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42., 43.,
        44., 45.]),
 array([47., 48., 49., 50., 51., 52., 53., 54., 55., 56., 57., 58., 59.,
        60., 61., 62., 63., 64.]),
 array([ 90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.,
        101., 102., 103., 104., 105., 106., 107., 108.]),
 array([127., 128., 129., 130., 131., 132., 133., 134., 135., 136., 137.]),
 array([143., 144., 145., 146., 147., 148., 149., 150., 151., 152., 153.,
        154., 155.]),
 array([174., 175., 176., 177., 178., 179., 180., 181., 182., 183., 184.,
        185., 186., 187., 188., 189., 190.]),
 array([229., 230., 231., 232., 233., 234., 235., 236., 237., 238., 239.,
        240., 241., 242., 243., 244., 245., 246., 247., 248., 249., 250.,
        251., 252., 253., 254., 255., 256., 257., 258.]),
 array([265., 266., 267., 268., 269., 270., 271., 272., 273., 274., 275.]),
 array([295., 296., 297., 298., 299., 300., 301., 302., 303., 304., 305.,
        306., 307.,

In [27]:
test_spec.spec.gross_spec_ser_an.calculated_step_counts

[array([390.18507446, 390.70341171, 392.35308517, 395.78780124,
        401.55585415, 410.03701383, 421.19007725, 434.11828827,
        446.27184417, 455.82994236, 462.38915904, 466.96344921,
        471.52019227, 471.52019227, 477.32916305]),
 array([487.6536149 , 487.08548427, 486.13907639, 484.55111832,
        482.41881598, 479.12604985, 469.78374578, 451.82480373,
        434.27316581, 421.73798426, 414.85087829, 411.65652424,
        408.41666718, 403.47895788, 398.96575187, 395.50874958,
        395.50874958, 395.13487679]),
 array([277.05627524, 275.81069106, 274.53128587, 273.2020172 ,
        271.80337075, 270.31598375, 268.73513811, 267.07438374,
        265.36553853, 263.65289788, 261.9700727 , 260.33419896,
        258.74874199, 257.21471392, 255.733478  , 254.30674859,
        252.9365912 , 252.9365912 , 251.81179276]),
 array([181.88042479, 183.92463754, 186.18307666, 188.70258034,
        191.47074381, 194.40252001, 197.3402196 , 200.08503309,
        202.52311957, 202.

In [28]:
test_spec.spec.gross_spec_ser_an.mix_regions

array([[  31,   46],
       [  47,   65],
       [  90,  109],
       [ 127,  138],
       [ 143,  156],
       [ 174,  191],
       [ 229,  259],
       [ 265,  276],
       [ 295,  357],
       [ 402,  432],
       [ 433,  478],
       [ 488,  516],
       [ 517,  522],
       [ 544,  557],
       [ 562,  569],
       [ 573,  588],
       [ 608,  639],
       [ 674,  695],
       [ 721,  738],
       [ 746,  759],
       [ 796,  807],
       [ 836,  857],
       [ 867,  901],
       [ 927,  942],
       [ 951,  978],
       [1000, 1017],
       [1023, 1040],
       [1084, 1099],
       [1123, 1156],
       [1182, 1213],
       [1288, 1297],
       [1308, 1319],
       [1363, 1373],
       [1376, 1387],
       [1393, 1406],
       [1426, 1443],
       [1474, 1491],
       [1497, 1508],
       [1531, 1548],
       [1590, 1603],
       [1605, 1622],
       [1663, 1670],
       [1692, 1701],
       [1741, 1762],
       [1791, 1808],
       [1825, 1838],
       [1839, 1848],
       [1868,

In [29]:
testexxx = [x.size for x in test_spec.spec.gross_spec_ser_an.chans_in_multiplets_list]
testexxx

[15,
 18,
 19,
 11,
 13,
 17,
 30,
 11,
 62,
 30,
 45,
 28,
 5,
 13,
 7,
 15,
 31,
 21,
 17,
 13,
 11,
 21,
 34,
 15,
 27,
 17,
 17,
 15,
 33,
 31,
 9,
 11,
 10,
 11,
 13,
 17,
 17,
 11,
 17,
 13,
 17,
 7,
 9,
 21,
 17,
 13,
 9,
 7,
 15,
 9,
 9,
 21,
 9,
 5,
 11,
 17,
 9,
 15,
 13]

In [30]:
testeyyy = [x.size for x in test_spec.spec.gross_spec_ser_an.calculated_step_counts]
testeyyy

[15,
 18,
 19,
 11,
 13,
 17,
 30,
 11,
 62,
 30,
 45,
 28,
 5,
 13,
 7,
 15,
 31,
 21,
 17,
 13,
 11,
 21,
 34,
 15,
 27,
 17,
 17,
 15,
 33,
 31,
 9,
 11,
 10,
 11,
 13,
 17,
 17,
 11,
 17,
 13,
 17,
 7,
 9,
 21,
 17,
 13,
 9,
 7,
 15,
 9,
 9,
 21,
 9,
 5,
 11,
 17,
 9,
 15,
 13]