In [1]:
# -*- coding: utf-8 -*-
"""
Created on Sat Jun  2 11:09:55 2018

@author: Marcelo
"""

import numpy as np
# 2019-03-15
# https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html
import pandas as pd
# 2019-03-09
from teste_datas import (Spec)
from scipy.signal import (cwt, ricker, find_peaks, find_peaks_cwt, peak_widths)
from scipy.optimize import (curve_fit, root)
from scipy.stats import (iqr)
import base_line_funcs as blf
import spectra_regions_funcs as spreg

# from spectra_regions_funcs import (total_analysis2)
import csv
import pickle
from bokeh.plotting import figure, output_file, output_notebook, show
from bokeh import palettes

In [2]:
def save_obj(obj, name ):
    with open('obj/'+ name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name ):
    with open('obj/' + name + '.pkl', 'rb') as f:
        return pickle.load(f)

In [3]:
# example 1:
# fn1 = r'../ipen/Relat_Eflu-gasosos_2018/Filtros/2018/CTP/CTP0706.Chn'
# 2019-03-04:
fn1 = r'../gamma/spectra/Filtros/2017/CTP/CTP2906.Chn'
chunksize = 32
with open(fn1, 'rb') as f:
    chunksize = 32
    chu1 = f.read(chunksize)
    lngtdt = np.frombuffer(chu1[30:32], dtype='u2')[0]
    chunksize = 4 * lngtdt
    chu2 = f.read(chunksize)
print(chu1)
rltime, lvtime = np.frombuffer(chu1[8:16], dtype='<u4')
print(rltime)
print(lvtime)
print(lngtdt)
counts = np.frombuffer(chu2, dtype='<u4')
print(counts)

# zz = np.dtype('uint32', yy)
# zz = int(yy)
# zz
              
# for b in bytes_from_file('../ipen/Relat_Eflu-gasosos_2018/Filtros/2018/CTP/CTP0706.Chn'):
#    # print(b)
#    a=1
#type(b)

b'\xff\xff\x03\x00\x01\x0010(\xf0\x03\x00\x90\xd0\x03\x0029Jun1710919\x00\x00\x00\x10'
258088
250000
4096
[0 0 0 ... 0 0 0]


In [4]:
fn2 = '../gamma/spectra/ALMERA-2017-3/ALM-17-3-#5_PreliA.IEC'
spec2 = Spec()
if spec2.readSp( fn2 ) >= 0:
    print (spec2.spLngData)

8192


In [15]:
# 2019-03-18 A saihda de scanSpec retorna o seguinte:
# return self.indicescwt, regions, multiplets
ret = spec2.scanSpec()
print (ret)

/home/maduar/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval


(array([ 108,  134,  237,  271,  380,  385,  392,  403,  443,  450,  456,
        706,  793,  934,  944,  958,  968,  995, 1189, 1209, 1226, 1311,
       1392, 1495, 1727, 1782, 1959, 1969, 1998, 2007, 2010, 2056, 2086,
       2093, 2146, 2243, 2304, 2317, 2339, 2401, 2418, 2434, 2468, 2586,
       2614, 2767, 2780, 2798, 2882, 2939, 2952, 2955, 3035, 3086, 3126,
       3370, 3373, 3523, 3541, 3568, 3572, 3616, 3629, 3646, 3674, 3684,
       3699, 3891, 3922, 3980, 3994, 4016, 4084, 4159, 4162, 4183, 4210,
       4250, 4309, 4379, 4479, 4484, 4505, 4509, 4516, 4550, 4573, 4659,
       4701, 4731, 4736, 4782, 4885, 4906, 4960, 4975, 5093, 5097, 5112,
       5129, 5170, 5305, 5603, 5647, 5675, 5682, 5744, 5795, 5852, 5855,
       5857, 5894, 5914, 5931, 5937, 5941, 6153, 6186, 6266, 6273, 6351,
       6380, 6488, 6491, 6493, 6589, 6702, 6706, 6809, 6843, 6927, 6979,
       6982, 7020, 7101, 7104, 7130, 7134, 7138, 7154, 7198, 7295, 7348,
       7372, 7403, 7412, 7463, 7501, 7567, 7598, 7

In [16]:
spec2.indicescwt[0]

108

In [17]:
spec2.defBlineRegionsSpec()

[[0, 95],
 [147, 224],
 [250, 258],
 [284, 367],
 [416, 430],
 [469, 693],
 [719, 780],
 [806, 921],
 [1008, 1176],
 [1239, 1298],
 [1324, 1379],
 [1405, 1482],
 [1508, 1714],
 [1740, 1769],
 [1795, 1946],
 [2023, 2043],
 [2106, 2133],
 [2159, 2230],
 [2256, 2291],
 [2352, 2388],
 [2447, 2455],
 [2481, 2573],
 [2627, 2754],
 [2811, 2869],
 [2895, 2926],
 [2968, 3022],
 [3048, 3073],
 [3099, 3113],
 [3139, 3357],
 [3386, 3510],
 [3585, 3603],
 [3712, 3878],
 [3904, 3909],
 [3935, 3967],
 [4029, 4071],
 [4097, 4146],
 [4223, 4237],
 [4263, 4296],
 [4322, 4366],
 [4392, 4466],
 [4529, 4537],
 [4586, 4646],
 [4672, 4688],
 [4749, 4769],
 [4795, 4872],
 [4919, 4947],
 [4988, 5080],
 [5142, 5157],
 [5183, 5292],
 [5318, 5590],
 [5616, 5634],
 [5695, 5731],
 [5757, 5782],
 [5808, 5839],
 [5870, 5881],
 [5954, 6140],
 [6166, 6173],
 [6199, 6253],
 [6286, 6338],
 [6393, 6475],
 [6506, 6576],
 [6602, 6689],
 [6719, 6796],
 [6822, 6830],
 [6856, 6914],
 [6940, 6966],
 [6995, 7007],
 [7033, 7088],

In [18]:
spec2.blinesFitSpec()

/home/maduar/ownCloud/Python_Scripts/teste_datas.py:271: RankWarning: Polyfit may be poorly conditioned
  zbl.append( np.polyfit(xbl[i], ybl[i], 2) )


0

In [19]:
lx = [ list(range(region[0], region[1]+1)) for region in spec2.regions ]
ly = [ [spec2.spCounts[i] for i in xs] for xs in lx ]

In [20]:
print(len(lx),len(ly),len(spec2.regions))

84 84 84


In [21]:
blins = [blf.bline_estimate_2(ys) for ys in ly ]
if blins:
    heis = [spec2.spCounts[i] for i in spec2.indicescwt]
    nety = [ [ gr-bl for gr, bl in zip(l1,l2) ] for l1,l2 in zip(ly,blins) ]

In [22]:
print(len(spec2.indicescwt),len(heis),len(nety))

163 163 84


In [23]:
# 2019-05-18 Tamanho da janela grahfica:
# Em tela de 23" usar 1600 x 900
# Na tela do note usar 1300 x 600

In [24]:
# default_plot_width  = 1300 
# default_plot_height =  600

default_plot_width  = 1600 
default_plot_height =  900

In [25]:
# 2019-05-12 Este eh o primeiro grahfico bokeh deste arquivo:

In [27]:
xs = np.linspace(0,spec2.spLngData-1,spec2.spLngData)
y0s = spec2.spCounts
p2 = figure(
   plot_width =default_plot_width,
   plot_height=default_plot_height,
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", y_range=[1.0, 10**5], title="Analyzed spectrum",
   x_axis_label='channels', y_axis_label='counts'
)
p2.circle(xs, y0s, legend="counts", color="lightblue",size=4)
p2.multi_line(lx,ly, legend="ly", color="orange")
p2.multi_line(lx,blins, legend="blins", color="magenta")
p2.multi_line(lx,nety, legend="nety", color="green")
p2.x(spec2.indicescwt, heis, legend="heis vs. spec2.indicescwt", color="red", size=6)
show(p2)

In [26]:
len(y0s)
np.var(y0s[0:50])

NameError: name 'y0s' is not defined

In [26]:
test1=[3,8,7]
test2=[4,4,8,9]
conca1=[test1,test2]
conca1

[[3, 8, 7], [4, 4, 8, 9]]

In [27]:
# 2019-05-16: Index tricks do Scipy
teste3 = np.concatenate(([3], [0]*5, np.arange(-1, 1.002, 2/9.0)))
teste3

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [28]:
teste4 = np.r_[3,[0]*5,-1:1:10j]
teste4

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [29]:
# Agora aplicando para o que quero:


In [30]:
widths = np.logspace(0.0,np.log10(15.0),num=30)
widths

array([ 1.        ,  1.09787999,  1.20534048,  1.3233192 ,  1.45284567,
        1.5950502 ,  1.7511737 ,  1.92257857,  2.11076055,  2.31736178,
        2.54418513,  2.79320995,  3.06660933,  3.36676903,  3.69630836,
        4.05810299,  4.45531009,  4.89139581,  5.3701656 ,  5.89579737,
        6.47287798,  7.10644323,  7.80202185,  8.56568369,  9.40409276,
       10.32456529, 11.33513367, 12.44461648, 13.66269546, 15.        ])

In [31]:
cwt1 = cwt(y0s, ricker, [1])[0]
cwtmatr = cwt(y0s, ricker, widths)
somas_escalas = np.sum(cwtmatr,axis=1)
print(len(somas_escalas))
print(somas_escalas)

30
[  52.92882605   64.78609965   51.1904766    62.12965354   74.64202792
  105.80683237   97.18299549  104.96614045  117.51879287  134.44020054
  159.87847451  210.19035597  214.89637696  242.16019613  293.49946899
  299.71496346  335.8365243   402.19175872  436.21804515  505.97494867
  550.13933111  586.32416921  657.61600886  771.06296009  836.57371895
  950.91813308 1075.11795498 1216.92823833 1383.11674266 1541.23323828]


In [32]:
# 2019-05-16 
half_window = 4
var_window = 2 * half_window + 1 
ksens = 2.0
ndx_scale_to_compare = 10
# 2019-05-16 Atualmente corresponde aa escala ....

midd_running_std_cwt1 =  [ np.std(cwt1[i:i+var_window]) for i in range(len(y0s)-var_window+1) ]
midd_running_iqr_cwt1 = [     iqr(cwt1[i:i+var_window]) for i in range(len(y0s)-var_window+1) ]
midd_running_mean_cwt1 = [np.mean(np.absolute(cwt1[i:i+var_window])) for i in range(len(y0s)-var_window+1) ]

running_std_cwt1 = np.r_[ [0]*half_window, midd_running_std_cwt1, [0]*half_window ]
running_iqr_cwt1 = np.r_[ [0]*half_window, midd_running_iqr_cwt1, [0]*half_window ]
running_mean_cwt1 = np.r_[ [0]*half_window, midd_running_mean_cwt1, [0]*half_window ]

# 2019-05-19 Usando std em vez de iqr
choose_signif_cts = [ (ksens*running_std_cwt1[i]) < cwtmatr[ndx_scale_to_compare][i] for i in range(len(running_std_cwt1))]


In [33]:
print(choose_signif_cts[0:30])

[False, False, False, False, False, True, False, True, True, True, True, False, False, False, True, False, True, True, False, False, True, True, True, True, False, True, True, True, False, False]


In [34]:
regions_cwt = []
if choose_signif_cts[0]:
    newreg = [0]
for i in range(1,len(choose_signif_cts)):
    if choose_signif_cts[i] and not choose_signif_cts[i-1]:
        newreg = [i]
    elif not choose_signif_cts[i] and choose_signif_cts[i-1]:
        newreg.append(i-1)
        regions_cwt.append(newreg)

In [35]:
regions_cwt

[[5, 5],
 [7, 10],
 [14, 14],
 [16, 17],
 [20, 23],
 [25, 27],
 [30, 30],
 [32, 32],
 [39, 39],
 [41, 43],
 [50, 50],
 [52, 54],
 [57, 57],
 [59, 65],
 [70, 70],
 [72, 79],
 [87, 87],
 [89, 89],
 [91, 91],
 [93, 94],
 [108, 114],
 [202, 205],
 [219, 222],
 [235, 238],
 [269, 272],
 [302, 307],
 [329, 330],
 [378, 381],
 [389, 393],
 [402, 404],
 [413, 413],
 [423, 427],
 [440, 445],
 [454, 458],
 [468, 471],
 [480, 482],
 [494, 497],
 [520, 520],
 [535, 537],
 [618, 619],
 [659, 659],
 [681, 681],
 [705, 706],
 [717, 719],
 [728, 729],
 [744, 745],
 [778, 779],
 [825, 828],
 [886, 886],
 [919, 921],
 [941, 946],
 [993, 996],
 [1006, 1009],
 [1017, 1022],
 [1057, 1061],
 [1072, 1073],
 [1096, 1097],
 [1105, 1106],
 [1207, 1211],
 [1224, 1228],
 [1242, 1244],
 [1309, 1313],
 [1364, 1364],
 [1370, 1370],
 [1389, 1394],
 [1422, 1424],
 [1471, 1471],
 [1493, 1497],
 [1518, 1523],
 [1544, 1545],
 [1555, 1555],
 [1589, 1593],
 [1614, 1614],
 [1638, 1640],
 [1661, 1662],
 [1686, 1690],
 [1711,

In [36]:
print(len(midd_running_std_cwt1), len(midd_running_std_cwt1), len(running_std_cwt1), len(running_iqr_cwt1))

8184 8184 8192 8192


In [37]:
len(choose_signif_cts)

8192

In [38]:
# xs = np.linspace(0,spec2.spLngData-1,spec2.spLngData)
# y0s = spec2.spCounts
p2a = figure(
   plot_width =default_plot_width,
   plot_height=default_plot_height,
   tools="pan,box_zoom,reset,save",
   # y_axis_type="log",
   y_range=[1.0, 10**5], title="Light blue counts, cwt1, running_mean_cwt1",
   x_axis_label='channels', y_axis_label='counts'
)
p2a.circle(xs, y0s, legend="counts", color="lightblue",size=4)
p2a.line(xs, cwt1, color="green", legend="cwt1")
p2a.line(xs, running_mean_cwt1, color="magenta", legend="running_mean_cwt1")
p2a.line(xs, running_std_cwt1, color="blue", legend="running_std_cwt1")
# [p2a.line(xs, cwtmatr[i], color=palettes.Plasma[11][i]) for i in range(1,7)]
p2a.line(xs, cwtmatr[ndx_scale_to_compare], color="red", legend="scale to compare")

# p2a.multi_line(lx,ly, color="orange")
# p2a.multi_line(lx,blins, color="magenta")
# p2a.multi_line(lx,nety, color="green")
# p2a.x(spec2.indicescwt, heis, color="red", size=6)
# p2a.line(xs, cwtmatr[0], color=palettes.Plasma[10][0])
# [p2a2.line(xs, cwtmatr[i], color=palettes.Plasma[11][i]) for i in range(7)]
# p2a2.line(xs, running_std_cwt1, color="blue", legend="std")
# p2a2.line(xs, running_iqr_cwt1, color="red",  legend="iqr" )
# p2a1.line(xs, mean_coeff_cwtmatr, color="orange", legend="MEAN")

show(p2a)

In [39]:
len(cwt1)

8192

In [40]:
lista1 = []
lista1.append(7)
lista1
list(range(7,10))

[7, 8, 9]

In [41]:
xs[regions_cwt[15][0]:regions_cwt[15][1]+1]

array([72., 73., 74., 75., 76., 77., 78., 79.])

In [42]:
# lx_cwt = [xs[il[0]:il[1]+1] for il in regions_cwt]
lx_cwt = [ list(range(region[0], region[1]+1)) for region in regions_cwt ]
ly_cwt = [ [spec2.spCounts[i] for i in xs] for xs in lx_cwt ]

In [43]:
widths

array([ 1.        ,  1.09787999,  1.20534048,  1.3233192 ,  1.45284567,
        1.5950502 ,  1.7511737 ,  1.92257857,  2.11076055,  2.31736178,
        2.54418513,  2.79320995,  3.06660933,  3.36676903,  3.69630836,
        4.05810299,  4.45531009,  4.89139581,  5.3701656 ,  5.89579737,
        6.47287798,  7.10644323,  7.80202185,  8.56568369,  9.40409276,
       10.32456529, 11.33513367, 12.44461648, 13.66269546, 15.        ])

In [44]:
palettes.Plasma[11]

['#0C0786',
 '#40039C',
 '#6A00A7',
 '#8F0DA3',
 '#B02A8F',
 '#CA4678',
 '#E06461',
 '#F1824C',
 '#FCA635',
 '#FCCC25',
 '#EFF821']

In [45]:
# xs = np.linspace(0,spec2.spLngData-1,spec2.spLngData)
# y0s = spec2.spCounts
p2b = figure(
   plot_width =default_plot_width,
   plot_height=default_plot_height,
   tools="pan,box_zoom,reset,save",
   y_range=[1.0, 10**5], title="CWT regions selection - y LIN",
   x_axis_label='channels', y_axis_label='counts'
)
p2b.circle(xs, y0s, legend="counts", color="lightblue",size=4)
p2b.multi_line(lx_cwt,ly_cwt, color="orange")
show(p2b)

In [46]:
# xs = np.linspace(0,spec2.spLngData-1,spec2.spLngData)
# y0s = spec2.spCounts
p2b1 = figure(
   plot_width =default_plot_width,
   plot_height=default_plot_height,
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", 
   y_range=[1.0, 10**5], title="CWT regions selection - y LOG",
   x_axis_label='channels', y_axis_label='counts'
)
p2b1.circle(xs, y0s, legend="counts", color="lightblue",size=4)
p2b1.multi_line(lx_cwt,ly_cwt, color="orange")
show(p2b1)

In [47]:
var_window

9

In [48]:
# 2019-05-16 Fazendo outra experiencia

In [49]:
somas_escalas = np.sum(cwtmatr,axis=1)
print(len(somas_escalas))
print(somas_escalas)

30
[  52.92882605   64.78609965   51.1904766    62.12965354   74.64202792
  105.80683237   97.18299549  104.96614045  117.51879287  134.44020054
  159.87847451  210.19035597  214.89637696  242.16019613  293.49946899
  299.71496346  335.8365243   402.19175872  436.21804515  505.97494867
  550.13933111  586.32416921  657.61600886  771.06296009  836.57371895
  950.91813308 1075.11795498 1216.92823833 1383.11674266 1541.23323828]


In [50]:
print(widths)

[ 1.          1.09787999  1.20534048  1.3233192   1.45284567  1.5950502
  1.7511737   1.92257857  2.11076055  2.31736178  2.54418513  2.79320995
  3.06660933  3.36676903  3.69630836  4.05810299  4.45531009  4.89139581
  5.3701656   5.89579737  6.47287798  7.10644323  7.80202185  8.56568369
  9.40409276 10.32456529 11.33513367 12.44461648 13.66269546 15.        ]


In [51]:
max_scales = np.argmax(cwtmatr,axis=0)
print(len(max_scales))
print(max_scales)

8192
[29 29 28 ... 23 11  0]


In [52]:
# o que estah acima eh inuhtil.
# Na verdade, preciso achar o mahximo absoluto dos coeficientes nas escalas em cada regiao. Assim:

In [53]:
# lx_cwt = [xs[il[0]:il[1]+1] for il in regions_cwt]
# lx_cwt = [ list(range(region[0], region[1]+1)) for region in regions_cwt ]
# ly_cwt = [ [spec2.spCounts[i] for i in xs] for xs in lx_cwt ]


In [54]:
# 2019-05-16 Definicao complicada...
coeffs_in_regions = [ [ [cwtmatr[scal,i] for i in xs] for xs in lx_cwt ] for scal in range(len(cwtmatr)) ]

In [55]:
lx_cwt

[[5],
 [7, 8, 9, 10],
 [14],
 [16, 17],
 [20, 21, 22, 23],
 [25, 26, 27],
 [30],
 [32],
 [39],
 [41, 42, 43],
 [50],
 [52, 53, 54],
 [57],
 [59, 60, 61, 62, 63, 64, 65],
 [70],
 [72, 73, 74, 75, 76, 77, 78, 79],
 [87],
 [89],
 [91],
 [93, 94],
 [108, 109, 110, 111, 112, 113, 114],
 [202, 203, 204, 205],
 [219, 220, 221, 222],
 [235, 236, 237, 238],
 [269, 270, 271, 272],
 [302, 303, 304, 305, 306, 307],
 [329, 330],
 [378, 379, 380, 381],
 [389, 390, 391, 392, 393],
 [402, 403, 404],
 [413],
 [423, 424, 425, 426, 427],
 [440, 441, 442, 443, 444, 445],
 [454, 455, 456, 457, 458],
 [468, 469, 470, 471],
 [480, 481, 482],
 [494, 495, 496, 497],
 [520],
 [535, 536, 537],
 [618, 619],
 [659],
 [681],
 [705, 706],
 [717, 718, 719],
 [728, 729],
 [744, 745],
 [778, 779],
 [825, 826, 827, 828],
 [886],
 [919, 920, 921],
 [941, 942, 943, 944, 945, 946],
 [993, 994, 995, 996],
 [1006, 1007, 1008, 1009],
 [1017, 1018, 1019, 1020, 1021, 1022],
 [1057, 1058, 1059, 1060, 1061],
 [1072, 1073],
 [1096

In [56]:

# 2016-05-15: PAREI AQUI: ver como achar o coef mahximo em cada regiao:
len(coeffs_in_regions)

30

In [ ]:
# factor for gaussian with fwhm
fgf = 4.0 * np.log(2.0)
fgf

In [ ]:

# Ateh agora: spLngData, spCounts, indicescwt, regions, multiplets, blin.

In [17]:
def gaussian_fw(x,*p):
    ng = int( len(p) / 3)
    a = 0.0
    for i in range(ng):
        fw, he, cn = p[3*i+0], p[3*i+1], p[3*i+2]
        a += he*np.exp(-fgf*(x-cn)**2/fw**2)
    return a

In [18]:
flatten = lambda l: [item for sublist in l for item in sublist]

In [19]:
lx_nonegat = []
nety_nonegat = []
sigma_nety = []
for i in range(len(lx[3])):
    if nety[3][i] > 0.0:
        lx_nonegat.append(lx[3][i])
        nety_nonegat.append(nety[3][i])
        sigma_nety.append(np.sqrt(nety[3][i]))
# (lx_nonegat,nety_nonegat,sigma_nety)

In [20]:
def no_negats(i, lx, nety):
    lx_nonegat = []
    nety_nonegat = []
    sigma_nety = []
    for j in range(len(lx[i])):
        if nety[i][j] > 0.0:
            lx_nonegat.append(lx[i][j])
            nety_nonegat.append(nety[i][j])
            sigma_nety.append(np.sqrt(nety[i][j]))
    return lx_nonegat, nety_nonegat, sigma_nety

In [21]:
xs

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 8.189e+03, 8.190e+03,
       8.191e+03])

In [22]:
spec0 = spec2

In [23]:
# Outra versao, usando fwhm
first_general_fit_fw = []
ini_fwhm = 6.0
for i in range(len(spec0.multiplets)):
    print(i)
    ipks = [j-spec0.regions[i][0] for j in spec0.multiplets[i]]
    try:
        multi_heis = [nety[i][ipk] for ipk in ipks]
    except (IndexError):
        print('Error: IndexError')
    else:
        inipars = [[ini_fwhm, i2,i3] for i2,i3 in zip(multi_heis, spec0.multiplets[i])]
        iniflat = flatten(inipars)
        #if len(lx_nonegat) < 3:
        #    print('Error: few points to fit.')
        #    break
        lx_nonegat, nety_nonegat, sigma_nety = no_negats(i, lx, nety)
        len_lx_nonegat = len(lx_nonegat)
        print('Length of lx_nonegat: ', len_lx_nonegat)
        fittd = True
        if len_lx_nonegat < 4:
            print('Error: few points to fit.')
            fittd = False
        else:
            try:
                popt_gauss1, pcov_gauss1 = curve_fit(gaussian_fw, lx_nonegat, nety_nonegat, sigma=sigma_nety, p0=iniflat)
            except (RuntimeError, TypeError):
                fittd = False
                print("Error: curve_fit failed.")
            if fittd:
                print(popt_gauss1)
                if np.inf in pcov_gauss1:
                    print('Matriz de covariancia ruim.')
                else:
                    print('Ajuste Ok.')
                    first_general_fit_fw.append( [lx_nonegat, nety_nonegat, popt_gauss1, pcov_gauss1] )
        print('-----------------------------')

0
Length of lx_nonegat:  41
Error: curve_fit failed.
-----------------------------
1
Length of lx_nonegat:  20
[   4.1352072  3195.8661026   236.36089566]
Ajuste Ok.
-----------------------------
2
Length of lx_nonegat:  20
[   3.96645789 2251.94181157  270.2616792 ]
Ajuste Ok.
-----------------------------
3
Length of lx_nonegat:  46
[ 4.61029775e+00  1.36853056e+04  3.79466321e+02  4.06554160e+00
 -9.61350776e+03  3.93258277e+02  5.09700277e+00  2.96735947e+04
  3.91581030e+02  4.68645885e+00  2.04441059e+03  4.02065081e+02]
Ajuste Ok.
-----------------------------
4
Length of lx_nonegat:  29
[ 5.29454084e+00  6.53143309e+03  4.42051221e+02  1.71536141e+01
 -1.00979038e+03  4.85893697e+00  4.65574129e+00  2.61265562e+03
  4.55510505e+02]
Matriz de covariancia ruim.
-----------------------------
5
Length of lx_nonegat:  14
[  1.661353   100.99718011 704.40263889]
Ajuste Ok.
-----------------------------
6
Length of lx_nonegat:  13
[  6.64282468  33.1313021  793.80395218]
Ajuste Ok.
--

/home/marcelo/anaconda3/lib/python3.7/site-packages/scipy/optimize/minpack.py:794: OptimizeWarning: Covariance of the parameters could not be estimated
  category=OptimizeWarning)



-----------------------------
15
Length of lx_nonegat:  31
[ 3.88091576e+00  6.52840840e+01  2.05401784e+03 -1.98050451e+02
  6.96729235e+01  1.87917488e+03  1.53066125e+00  2.14511914e+01
  2.09248768e+03]
Ajuste Ok.
-----------------------------
16
Length of lx_nonegat:  13
Error: curve_fit failed.
-----------------------------
17
Length of lx_nonegat:  14
[  -8.98816172   31.56226223 2241.54591082]
Ajuste Ok.
-----------------------------
18
Length of lx_nonegat:  43
[   5.70322857  130.98925928 2302.83755635    5.43922021   25.15853421
 2318.34409772    8.07712099   75.8242176  2339.71319775]
Ajuste Ok.
-----------------------------
19
Length of lx_nonegat:  35
[   4.30727092   46.21007792 2401.06305192    8.31554617   23.58600303
 2416.33570693    5.54929774  147.23317553 2432.27930198]
Ajuste Ok.
-----------------------------
20
Length of lx_nonegat:  15
[   7.41550929  103.24439875 2464.66992533]
Ajuste Ok.
-----------------------------
21
Length of lx_nonegat:  52
[  12.373475

In [24]:
#  Versao com fw em vez de sh
list_fwhms = []
list_channs = []
list_unc_fwhms = []
for i in range(len(first_general_fit_fw)):
    parms, cov_parms = first_general_fit_fw[i][2:4] 
    fwhms_inds = [j*3 for j in range(len(parms)//3)]
    fwhms = [parms[j] for j in fwhms_inds]
    unc_fwhms = [np.sqrt(cov_parms[j,j]) for j in fwhms_inds]
    channs_inds = [j*3+2 for j in range(len(parms)//3)]
    channs = [parms[j] for j in channs_inds]
    unc_channs = [np.sqrt(cov_parms[j,j]) for j in channs_inds]
    for k in range(len(fwhms)):
        if fwhms[k] > 0.0 and unc_fwhms[k]/fwhms[k] < 0.15:
            list_channs.append(channs[k])
            list_fwhms.append(fwhms[k])
            list_unc_fwhms.append(unc_fwhms[k])

In [25]:
channs=np.array(list_channs)
fwhms=np.array(list_fwhms)
unc_fwhms=np.array(list_unc_fwhms)
sqrt_channs = np.sqrt(channs)
weis = np.array(unc_fwhms)**-2
coeff_fwhm_fit, covar_fwhm_fit = np.polyfit(sqrt_channs, fwhms, deg=1, w=weis, cov=True)
poly1 = np.poly1d(coeff_fwhm_fit)
fit1 = poly1(sqrt_channs)

coeff_fwhm_fit, covar_fwhm_fit, fit1

(array([0.09169161, 1.77766031]), array([[ 2.52126925e-06, -1.21724772e-04],
        [-1.21724772e-04,  6.01191993e-03]]), array([ 3.18733011,  3.28503708,  3.56380321,  3.5920911 ,  3.61622012,
         4.59380264,  4.96524765,  4.98763579,  5.09790476,  5.19713707,
         5.32284834,  5.64826436,  6.17774703,  6.2128367 ,  6.29972016,
         6.32973068,  6.44013191,  6.74767033,  6.87079671,  7.49752269,
         7.56234375,  7.59066935,  7.63662808,  7.68993427,  7.75448787,
         8.08452604,  8.18559721,  8.20169724,  8.68576463,  8.79143965,
         9.03991479,  9.45991277,  9.87316009,  9.8860791 ,  9.99111384,
        10.01878352]))

In [26]:
unc_fwhms, weis

(array([0.10604763, 0.11314764, 0.10918141, 0.61428365, 0.40534344,
        0.07468659, 0.13511985, 0.04352587, 0.32530408, 0.43527354,
        0.05600556, 0.02254538, 0.33681189, 0.72509353, 0.42683563,
        0.78541994, 0.83351355, 0.43059479, 0.02232954, 0.09733711,
        0.18922077, 1.68186548, 0.2209771 , 1.58286235, 0.34078212,
        0.27039347, 0.62643055, 0.62973673, 1.28746099, 1.06223145,
        0.28782738, 0.43394449, 1.29913821, 1.12898863, 0.93420996,
        1.29888449]),
 array([8.89197238e+01, 7.81104300e+01, 8.38885316e+01, 2.65009897e+00,
        6.08630499e+00, 1.79272956e+02, 5.47723890e+01, 5.27843468e+02,
        9.44976447e+00, 5.27807385e+00, 3.18814207e+02, 1.96736538e+03,
        8.81505810e+00, 1.90200628e+00, 5.48881586e+00, 1.62104903e+00,
        1.43937739e+00, 5.39339781e+00, 2.00558163e+03, 1.05546318e+02,
        2.79294493e+01, 3.53522847e-01, 2.04788453e+01, 3.99129382e-01,
        8.61085741e+00, 1.36775277e+01, 2.54832102e+00, 2.52163344e+00

In [27]:
fwhms, channs

(array([ 4.1352072 ,  3.96645789,  4.61029775,  5.09700277,  4.68645885,
         4.79129427,  4.54457326,  5.1619671 ,  5.28824981,  6.95932507,
         5.35171745,  5.61153088,  5.70322857,  8.07712099,  5.54929774,
         7.41550929, 12.37347568,  6.27535811,  6.88682614,  7.60932464,
         8.79704749, 12.25074079,  7.06817945, 11.97249434,  7.79628717,
         8.39765205,  7.69666858,  6.97803013,  8.59037169,  9.75050288,
         8.80045858, 10.82216604, 12.84513466,  9.89797656, 10.9182144 ,
        10.32289648]),
 array([ 236.36089566,  270.2616792 ,  379.46632086,  391.58103049,
         402.06508149,  943.30042994, 1208.55110285, 1225.58732502,
        1311.23625999, 1390.7854713 , 1494.92491302, 1781.96153674,
        2302.83755635, 2339.71319775, 2432.27930198, 2464.66992533,
        2585.67079379, 2938.02414528, 3085.39979284, 3891.4548035 ,
        3980.15537524, 4019.22971381, 4083.0344957 , 4157.66918589,
        4248.95648738, 4731.16399516, 4884.01832432, 4908.

In [28]:
# Definindo fun,c~ao com fwhms fixos
def gaus_fix_fw(*fws):
    def g2(x, *hescns): # HEightS, COuntS
        pcompl = np.array([])
        ng = int( len(hescns) / 2)
        for i in range(ng):
            pcompl = np.append(pcompl, (fws[i], hescns[2*i+0], hescns[2*i+1]))
        return gaussian_fw(x,*pcompl)
    return g2

In [29]:
second_general_fit = []
for i in range(len(first_general_fit_fw)):
    # 2018-07-02
    # AQUI: fazer a segunda passada do ajuste, usando agora fwhms fixos.
    # Todos os dados estao na lista first_general_fit_fw
    ipks = len(first_general_fit_fw[i][2])//3
    print('#',i,': ','peaks: ', ipks)
    xs2 = first_general_fit_fw[i][0]
    ys2 = first_general_fit_fw[i][1]
    teste1 = first_general_fit_fw[i][2]
    fwstest = []
    hestest = []
    cnstest = []
    [fwstest.append(teste1[3*j]) for j in range(len(teste1)//3)]
    [hestest.append(teste1[3*j+1]) for j in range(len(teste1)//3)]
    [cnstest.append(teste1[3*j+2]) for j in range(len(teste1)//3)]
    fws_fit = poly1(np.sqrt(cnstest))
    p0=[]
    [p0.extend((j1, j2)) for j1,j2 in zip(hestest, cnstest)]
    print('fws_fit: ', fws_fit)
    print('p0: ', p0)
    fittd = True
    try:
        popt2, pcov2 = curve_fit(gaus_fix_fw(*fws_fit), xs2, ys2, p0=p0)
    except RuntimeError:
        fittd = False
        print("Error: curve_fit failed.")
    if fittd:
        print('popt2: ', popt2)
        if np.inf in pcov2:
            print('Matriz de covariancia ruim.')
        else:
            print('Ajuste Ok.')
            second_general_fit.append( [xs2, ys2, fws_fit, popt2, pcov2] )
    print('-----------------------------')
# second_general_fit

# 0 :  peaks:  1
fws_fit:  [3.18733011]
p0:  [3195.866102602346, 236.36089566347565]
popt2:  [3569.54876328  236.38996385]
Ajuste Ok.
-----------------------------
# 1 :  peaks:  1
fws_fit:  [3.28503708]
p0:  [2251.941811565876, 270.26167919967526]
popt2:  [2428.57504979  270.15855821]
Ajuste Ok.
-----------------------------
# 2 :  peaks:  4
fws_fit:  [3.56380321 3.59597279 3.5920911  3.61622012]
p0:  [13685.305589647807, 379.4663208584113, -9613.507762805948, 393.2582774659104, 29673.594699035402, 391.5810304911541, 2044.4105850701228, 402.065081485335]
popt2:  [15510.33682532   379.48594427 16938.14049087   391.89942389
 13577.94686949   389.8354403   2325.85321372   402.06273144]
Ajuste Ok.
-----------------------------
# 3 :  peaks:  1
fws_fit:  [4.21120917]
p0:  [100.99718010535219, 704.4026388937463]
popt2:  [ 39.87703076 704.60797939]
Ajuste Ok.
-----------------------------
# 4 :  peaks:  1
fws_fit:  [4.36102793]
p0:  [33.13130209805476, 793.8039521770511]
popt2:  [ 70.3908849

In [30]:
print(second_general_fit)

[[[228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 245, 246, 247, 248], [16.944801949894327, 10.012707186015291, 14.037803787671805, 75.2217133211484, 143.63643281834095, 525.9700451578852, 1237.3706304364891, 2396.922166143834, 3067.6008766170535, 2972.468344145257, 2151.4695855082873, 1060.0104914597514, 380.6154244041694, 87.01410956249174, 7.683507257503152, 19.636200068613675, 86.81829170667663, 31.000483575258272, 47.04584273528553, 52.18918798114794], array([3.18733011]), array([3569.54876328,  236.38996385]), array([[2.72344327e+04, 1.50194009e-05],
       [1.50194009e-05, 7.83177133e-03]])], [[259, 263, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 279, 280, 281, 282, 283], [22.066504992227806, 0.7752194390194518, 38.69337999693926, 41.95242715924246, 389.1297240065751, 1046.8060284539865, 1801.2201508826788, 2158.8537757239487, 1936.2166522691841, 1282.7375373558546, 646.6965318993189, 226.41901422056765, 51.94265411899869, 3

In [31]:



xs = np.linspace(0,spec0.spLngData-1,spec0.spLngData)
y0s = spec0.spCounts
padj = figure(
   plot_width=1500,
   plot_height=1000,
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", y_range=[1.0, 10**3], title="Analyzed spectrum",
   x_axis_label='channels', y_axis_label='counts'
)
padj.circle(xs, y0s, legend="counts", color="lightblue",size=3)
padj.multi_line(lx,ly, color="orange")
padj.multi_line(lx,blins, color="magenta")
padj.multi_line(lx,nety, color="green")
padj.x(spec0.indicescwt, heis, color="red", size=6)

# 2018-Jul-03: Falta fazer a soma blin com o ajuste:
# dummy = [ ax1.semilogy(z[0], gaus_fix_fw(*z[2])(z[0], *z[3]), marker='o', color='blue', linewidth=1.0) for z in second_general_fit ]
# Usando linspace: usar pontos extremos de z[0] para construir a faixa
for z in second_general_fit:
    xra = np.linspace(z[0][0], z[0][-1], num=int(np.around(z[0][-1]-z[0][0]))+1)
    ax1.semilogy(xra, gaus_fix_fw(*z[2])(xra, *z[3]), marker='o', color='yellow', linewidth=1.0)
dummy = [ ax1.semilogy(xs, ys, marker='x', color='red', linestyle='None') for xs,ys in zip(indics,heis) ]




show(padj)



NameError: name 'ax1' is not defined

In [32]:
plt.close('all')
fig1, ax1 = plt.subplots(1, 1, figsize=(20,12))
ax1.grid(True)
ax1.set_xlim(1170, 1250)
ax1.set_ylim(3.0, 1e5)
ax1.set_xlabel('Canal', size=20)
ax1.set_ylabel('Contagens', size=20)
ax1.semilogy(xs, cts_spc, marker='.', markersize=2.0, color='lightgreen', linestyle='None')
dummy = [ ax1.semilogy(xs, ys, marker='', color='lightgreen', linewidth=0.5) for xs,ys in zip(lx,ly) ]
dummy = [ ax1.semilogy(xs, ys, marker='', color='beige', linewidth=1.0) for xs,ys in zip(lx,blins) ]
dummy = [ ax1.semilogy(xs, ys, marker='x', color='magenta', linewidth=1.0) for xs,ys in zip(lx,nety) ]

# 2018-Jul-03: Falta fazer a soma blin com o ajuste:
# dummy = [ ax1.semilogy(z[0], gaus_fix_fw(*z[2])(z[0], *z[3]), marker='o', color='blue', linewidth=1.0) for z in second_general_fit ]
# Usando linspace: usar pontos extremos de z[0] para construir a faixa
for z in second_general_fit:
    xra = np.linspace(z[0][0], z[0][-1], num=int(np.around(z[0][-1]-z[0][0]))+1)
    ax1.semilogy(xra, gaus_fix_fw(*z[2])(xra, *z[3]), marker='o', color='yellow', linewidth=1.0)
dummy = [ ax1.semilogy(xs, ys, marker='x', color='red', linestyle='None') for xs,ys in zip(indics,heis) ]

NameError: name 'plt' is not defined

In [33]:
plt.close('all')
fig1, ax1 = plt.subplots(1, 1, figsize=(15,9))
ax1.grid(True)
ax1.set_xlim(0, 8500)
ax1.set_ylim(0.0, 15.0)
dummy = ax1.plot(channs, fwhms, marker='x', color='red', linestyle='None')
dummy = ax1.errorbar(channs, fwhms, yerr=unc_fwhms, capsize=5.0, color='orange', linestyle='None')
dummy = ax1.plot(channs, fit1, color='lightblue')
fig1

NameError: name 'plt' is not defined

In [34]:
# Agora espectros totalmente diferentes: espectro .chn de efluente CTP...

In [35]:
fn3 = r'../gamma/spectra/Filtros/2017/CTP/CTP2906.Chn'
spec3 = Spec()
if spec3.readSp( fn3 ) >= 0:
    print (spec3.spLngData)

4096


In [36]:
ret = spec3.scanSpec()
spec3.defBlineRegionsSpec()
spec3.blinesFitSpec()

/home/marcelo/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval


0

In [37]:
lx = [ list(range(region[0], region[1]+1)) for region in spec3.regions ]
ly = [ [spec3.spCounts[i] for i in xs] for xs in lx ]

In [38]:
blins = [blf.bline_estimate_2(ys) for ys in ly ]
if blins:
    heis = [spec3.spCounts[i] for i in spec3.indicescwt]
    nety = [ [ gr-bl for gr, bl in zip(l1,l2) ] for l1,l2 in zip(ly,blins) ]

In [39]:
xs = np.linspace(0,spec3.spLngData-1,spec3.spLngData)
y0s = spec3.spCounts
p3 = figure(
   plot_width=1500,
   plot_height=1000,
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", y_range=[1.0, 10**3], title="Analyzed spectrum",
   x_axis_label='channels', y_axis_label='counts'
)
p3.circle(xs, y0s, legend="counts", color="lightblue",size=4)
p3.multi_line(lx,ly, color="orange")
p3.multi_line(lx,blins, color="magenta")
p3.multi_line(lx,nety, color="green")
p3.x(spec3.indicescwt, heis, color="red", size=6)
show(p3)

In [37]:
# .. e de efluente CRN

In [38]:
fn4 = r'../gamma/spectra/Filtros/2017/CRN/CRN2906.Chn'
spec4 = Spec()
if spec4.readSp( fn4 ) >= 0:
    print (spec4.spLngData)

4096


In [39]:
ret = spec4.scanSpec()
spec4.defBlineRegionsSpec()
spec4.blinesFitSpec()

/home/marcelo/anaconda3/lib/python3.7/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
/home/marcelo/ownCloud/Python_Scripts/teste_datas.py:257: RankWarning: Polyfit may be poorly conditioned
  zbl.append( np.polyfit(xbl[i], ybl[i], 2) )


0

In [40]:
lx = [ list(range(region[0], region[1]+1)) for region in spec4.regions ]
ly = [ [spec4.spCounts[i] for i in xs] for xs in lx ]

In [41]:
blins = [blf.bline_estimate_2(ys) for ys in ly ]
if blins:
    heis = [spec4.spCounts[i] for i in spec4.indicescwt]
    nety = [ [ gr-bl for gr, bl in zip(l1,l2) ] for l1,l2 in zip(ly,blins) ]

In [42]:
xs = np.linspace(0,spec4.spLngData-1,spec4.spLngData)
y0s = spec4.spCounts
p4 = figure(
   plot_width=1500,
   plot_height=1000,
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", y_range=[1.0, 10**3], title="Analyzed spectrum",
   x_axis_label='channels', y_axis_label='counts'
)
p4.circle(xs, y0s, legend="counts", color="lightblue",size=4)
p4.multi_line(lx,ly, color="orange")
p4.multi_line(lx,blins, color="magenta")
p4.multi_line(lx,nety, color="green")
p4.x(spec4.indicescwt, heis, color="red", size=6)
show(p4)

In [43]:
# 2019-mar: testes com gravacao

In [44]:
with open('teste-csv.csv', 'w') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(vars(spec3).items())

In [45]:
with open('teste-csv.csv', 'w') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerows(vars(spec3).items())

In [46]:
save_obj(spec2, 'arquivo1')

In [47]:
spec2_loaded = load_obj('arquivo1')

In [48]:
save_obj(spec3, 'arquivo2')

In [49]:
spec3_loaded = load_obj('arquivo2')

In [50]:
# 2019-03-15
# PAREI AQUI: Usar Pandas para continuar o desenvolvimento.