In [52]:
import numpy as np
import numpy.random as npr
# Do this (new version)
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(10)
more_vals = rng.standard_normal(10)

In [18]:
xs=np.asarray(range(13,50))
xs

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [19]:
xs[0:10]+xs[10:20]

array([36, 38, 40, 42, 44, 46, 48, 50, 52, 54])

In [20]:
testarr = np.array(xs[10:20])
testarr

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [21]:
testarr

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [22]:
sum(testarr)

275

In [23]:
firstprimes = np.array([2,3,5,7,11,13,17,19,23,29])
firstprimes

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [24]:
testarr + firstprimes

array([25, 27, 30, 33, 38, 41, 46, 49, 54, 61])

In [25]:
np.sum([testarr, firstprimes],axis=0)

array([25, 27, 30, 33, 38, 41, 46, 49, 54, 61])

In [26]:
np.sum([testarr, firstprimes],axis=1)

array([275, 129])

In [27]:
testarr

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [28]:
testarr[2:5] += firstprimes[4:7]

In [29]:
testarr

array([23, 24, 36, 39, 44, 28, 29, 30, 31, 32])

In [30]:
7==7==7

True

In [31]:
7==7==8

False

In [32]:
7 in range(5,8)

True

In [33]:
7 in range(5,7)

False

In [35]:
range(5,7) in range(2,13)

False

In [46]:
chPks=npr.randint(4,size=100)
chPks

array([0, 3, 3, 1, 1, 2, 0, 1, 3, 2, 1, 2, 1, 2, 3, 1, 3, 0, 2, 0, 1, 2,
       0, 0, 0, 2, 3, 1, 0, 2, 0, 0, 1, 3, 1, 1, 2, 3, 3, 3, 2, 0, 3, 3,
       3, 3, 2, 2, 0, 0, 1, 1, 0, 3, 0, 1, 0, 3, 2, 0, 0, 3, 2, 2, 3, 1,
       0, 2, 1, 1, 0, 0, 0, 3, 2, 1, 3, 0, 3, 0, 3, 1, 2, 2, 2, 0, 1, 3,
       0, 0, 1, 3, 2, 0, 3, 2, 0, 3, 0, 2])

In [47]:
chPks=npr.randint(8000,size=500)

In [51]:
sideChs = npr.randint(low=2,high=15,size=chPks.size)
sideChs

array([ 2, 14,  6, 13,  7,  9, 14,  6,  6,  8, 13, 11, 14, 13,  6,  2,  8,
       14,  5,  2,  6,  2,  6,  3,  6, 13, 14, 10, 11, 14, 10, 11, 11, 13,
       14, 11, 10, 13, 11,  8, 11, 11,  3,  5, 13,  5,  3, 11, 11, 10, 10,
        7, 14,  2,  5,  8,  5,  7,  5, 12, 13,  3,  4, 14, 12,  7,  7, 11,
       11,  6,  9,  8,  6,  3,  6,  5,  8,  8,  2,  9,  8, 10, 14,  5,  7,
        8, 12, 13, 14, 11,  6,  2,  3,  7, 12, 10,  6,  9,  3, 13,  4,  9,
        2,  9, 11, 12, 13, 10,  5,  4,  7, 11,  3,  8,  5, 12, 12,  5, 12,
       11,  8,  5, 11,  5, 11, 12, 14,  4,  2,  8, 14,  3,  8, 10,  5,  5,
        2,  6, 13, 11,  9,  6,  8, 12,  6, 10, 10,  4, 11,  8,  3,  4, 11,
        3, 12,  4,  5,  4,  8,  6, 13,  5,  8,  4, 13,  3,  9,  9, 10, 10,
        6,  5,  4, 10,  2, 13,  7,  3, 12,  8, 10,  6,  3,  8, 12,  9, 14,
       10, 10,  4,  8,  4, 10, 13, 12, 10, 13, 13,  4,  4,  4, 12, 12,  3,
        7, 10,  5,  9,  9,  7,  7,  5, 13, 11,  7,  3, 10,  4, 12,  2, 14,
        2, 13, 12,  2,  4

In [53]:
vals

array([-1.24365545, -0.63660639,  1.00775455,  1.87677145,  1.53758085,
        0.15589889,  1.81843007, -0.74017808, -0.69988847, -0.17754583])

In [54]:
from numpy.random import default_rng

rg = default_rng(12345)

print(rg)
# Generator(PCG64)

print(rg.random())
# 0.22733602246716966

Generator(PCG64)
0.22733602246716966


In [55]:
rng = np.random.default_rng(seed=42)

arr2 = rng.random((3, 3))

arr2
#array([[0.77395605, 0.43887844, 0.85859792],
#       [0.69736803, 0.09417735, 0.97562235],
#       [0.7611397 , 0.78606431, 0.12811363]])


array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])