In [1]:
import numpy as np
import numpy.random as npr
import struct as stru
# Do this (new version)
from numpy.random import default_rng
rng = default_rng()
vals = rng.standard_normal(10)
more_vals = rng.standard_normal(10)

In [2]:
!echo $PATH

/snap/jupyter/6/bin:/snap/jupyter/6/usr/sbin:/snap/jupyter/6/usr/bin:/snap/jupyter/6/sbin:/snap/jupyter/6/bin:/home/marcelo/snap/jupyter/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games


In [3]:
!type python

python is /snap/jupyter/6/bin/python


In [5]:
paths = !type -a python
for path in set(paths):
    path = path.split()[-1]
    print(path)
    !{path} -c "import sys; print(sys.path)"
    print()

/snap/jupyter/6/bin/python
['', '/snap/jupyter/6/lib/python37.zip', '/snap/jupyter/6/lib/python3.7', '/snap/jupyter/6/lib/python3.7/lib-dynload', '/home/marcelo/snap/jupyter/common/lib/python3.7/site-packages', '/snap/jupyter/6/lib/python3.7/site-packages']



In [6]:
import time

In [7]:
testarr = np.ones(10)*7

In [8]:
firstprimes = np.array([2,3,5,7,11,13,17,19,23,29])
firstprimes

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [9]:
np.sum([testarr, firstprimes],axis=0)

array([ 9., 10., 12., 14., 18., 20., 24., 26., 30., 36.])

In [10]:
displaced = np.zeros(10)
displaced[3:6] += firstprimes[2:5]
displaced

array([ 0.,  0.,  0.,  5.,  7., 11.,  0.,  0.,  0.,  0.])

In [11]:
sli = slice(3,6)
sli

slice(3, 6, None)

In [12]:
np.asarray(range(sli.start, sli.stop))

array([3, 4, 5])

In [13]:
displaced[sli]

array([ 5.,  7., 11.])

In [14]:
np.sum([testarr, firstprimes],axis=1)

array([ 70., 129.])

In [15]:
testarr

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [16]:
testarr[2:5] += firstprimes[4:7]

In [17]:
testarr

array([ 7.,  7., 18., 20., 24.,  7.,  7.,  7.,  7.,  7.])

In [18]:
7==7==7

True

In [19]:
7==7==8

False

In [20]:
7 in range(5,8)

True

In [21]:
7 in range(5,7)

False

In [22]:
range(5,7) in range(2,13)

False

In [23]:
regioes = np.array([1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [24]:
n = regioes.size
n

23

In [25]:
comuta = np.zeros(n)
for i in range(1,n):
    comuta[i] = regioes[i] - regioes[i-1]
comuta

array([ 0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  1.,  0.,  0., -1.,  0.,
        1.,  0.,  0.,  0., -1.,  0.,  0.,  1.,  0.,  0.])

In [26]:
inis = np.insert(np.nonzero(comuta>0), 0, 0)
inis

array([ 0,  8, 13, 20])

In [27]:
fins = np.append(np.nonzero(comuta<0), n)
fins

array([ 5, 11, 17, 23])

In [28]:
mix = np.concatenate(np.array([[inis], [fins]])).T
mix

array([[ 0,  5],
       [ 8, 11],
       [13, 17],
       [20, 23]])

In [29]:
mix.shape

(4, 2)

In [ ]:
# 2022-set-27
# Montando listas de arrays com Nones intercalados para plotar

In [60]:
rng.integers(4, size=10)

array([1, 2, 3, 0, 1, 2, 1, 0, 2, 3])

In [87]:
arlist = [np.concatenate((rng.integers(100, size=i[1]-i[0]), [None])) for i in mix]
arlist

[array([14, 19, 3, 61, 85, None], dtype=object),
 array([9, 19, 39, None], dtype=object),
 array([80, 62, 11, 57, None], dtype=object),
 array([92, 85, 47, None], dtype=object)]

In [89]:
# AQUI: usarei isto para plotar "poli-linhas"!
# Mais simples e direto:
arlist = [np.append(rng.integers(100, size=i[1]-i[0]), None) for i in mix]
arlist

[array([49, 56, 9, 53, 55, None], dtype=object),
 array([33, 7, 55, None], dtype=object),
 array([20, 86, 11, 30, None], dtype=object),
 array([69, 6, 38, None], dtype=object)]

In [90]:
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate
np.concatenate(arlist)

array([49, 56, 9, 53, 55, None, 33, 7, 55, None, 20, 86, 11, 30, None, 69,
       6, 38, None], dtype=object)

In [81]:
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate
np.concatenate(arlist, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [75]:
# https://numpy.org/doc/stable/reference/generated/numpy.block.html#numpy-block
np.block(arlist)

array([35, 77, 11, 61, 69, 10, 25, 63, 49, 90, 29, 42, 16, 16, 40])

In [77]:
# https://numpy.org/doc/stable/reference/generated/numpy.stack.html#numpy.stack
np.stack(arlist)

ValueError: all input arrays must have the same shape

In [ ]:
arlistwithnones = 

In [30]:
time()

TypeError: 'module' object is not callable

In [31]:
nPks = 300

In [32]:
chPks=npr.randint(8000,size=nPks)

In [33]:
sideChs = npr.randint(low=2,high=15,size=nPks)

In [34]:
rg = default_rng(137)
cwt = rng.random(size=nPks)

In [35]:
cnts = []
fn = '../Genie_Transfer/Si/SI2019/SI04019.Chn'

try:
    fi = open(fn, 'rb')
except (FileNotFoundError, IOError):
    print(r'Erro de arquivo CHN!!!')
else:
    ctn = fi.read()
    fi.close()

Erro de arquivo CHN!!!


In [36]:
len(ctn)

NameError: name 'ctn' is not defined

In [37]:
type(ctn)

NameError: name 'ctn' is not defined

In [38]:
16928-256

16672

In [39]:
ctn[16672:16928]

NameError: name 'ctn' is not defined

In [40]:
inifin = 16928-512
inifin

16416

In [41]:
ctn[inifin:inifin+28]

NameError: name 'ctn' is not defined

In [42]:
eh_int = ctn[inifin:inifin+2]
eh_int

NameError: name 'ctn' is not defined

In [43]:
# 2020-09-18 Identificador do tipo de arquivo.
# -102 indica o formato mais novo de CHN
# ORTEC File Structures.pdf

quero_int = int.from_bytes(eh_int, byteorder='little', signed=True)
quero_int 

NameError: name 'eh_int' is not defined

In [44]:
eh_float = ctn[inifin+4:inifin+8]
eh_float

NameError: name 'ctn' is not defined

In [45]:
stru.unpack('f', eh_float)

NameError: name 'eh_float' is not defined

In [46]:
eh_float = ctn[inifin+8:inifin+12]
eh_float

NameError: name 'ctn' is not defined

In [47]:
stru.unpack('f', eh_float)

NameError: name 'eh_float' is not defined

In [48]:
spChOffset  = int.from_bytes(ctn[28:30], byteorder='little', signed=False)
spLngData   = int.from_bytes(ctn[30:32], byteorder='little', signed=False)
inicounts = spChOffset + 32
spCounts = [ int.from_bytes(ctn[inicounts+i*4:inicounts+(i+1)*4], byteorder='little',
                            signed=False)
            for i in range(spLngData) ]
iBy = inicounts + 4*spLngData
coeffs_ChEn_0 = stru.unpack('f', ctn[iBy+4:iBy+8])
coeffs_ChEn_1 = stru.unpack('f', ctn[iBy+8:iBy+12])
coeffs_ChEn_2 = stru.unpack('f', ctn[iBy+12:iBy+16])

NameError: name 'ctn' is not defined

In [49]:
[coeffs_ChEn_0[0], coeffs_ChEn_1[0], coeffs_ChEn_2[0]]

NameError: name 'coeffs_ChEn_0' is not defined

In [50]:
coeffs_EnFw_0 = stru.unpack('f', ctn[iBy+16:iBy+20])
coeffs_EnFw_1 = stru.unpack('f', ctn[iBy+20:iBy+24])
coeffs_EnFw_2 = stru.unpack('f', ctn[iBy+24:iBy+28])

NameError: name 'ctn' is not defined

In [51]:
[coeffs_EnFw_0[0], coeffs_EnFw_1[0], coeffs_EnFw_2[0]]

NameError: name 'coeffs_EnFw_0' is not defined

In [52]:
detDescrLen  = int(ctn[iBy+256])
detDescrLen

NameError: name 'ctn' is not defined

In [53]:
detDescr  = ctn[iBy+257:iBy+257+detDescrLen].decode('ascii')
detDescr

NameError: name 'ctn' is not defined

In [54]:
samDescrLen  = int(ctn[iBy+320])
samDescrLen

NameError: name 'ctn' is not defined

In [55]:
samDescr  = ctn[iBy+321:iBy+321+samDescrLen].decode('ascii')
samDescr

NameError: name 'ctn' is not defined

In [56]:
detDescrLen  = int(ctn[iBy+256])
detDescr  = ctn[iBy+257:iBy+257+detDescrLen].decode('ascii')
samDescrLen  = int(ctn[iBy+320])
samDescr  = ctn[iBy+321:iBy+321+samDescrLen].decode('ascii')

NameError: name 'ctn' is not defined