In [1]:
import numpy as np
import numpy.ma as ma  # masked array
from numpy.polynomial import Polynomial as P # 2020-09-06 Esta é a nova classe recomendada 
from numpy import linalg as LA

# https://realpython.com/python-import/
# https://docs.python-guide.org/writing/structure/

import scipy.stats as sta # statistics
# from scipy.stats import norm
# from scipy.special import (erf, erfinv)
import scipy.special as spsp
from scipy.optimize import curve_fit
# import scipy.optimize as spoptim
# 2020-08-30
from scipy import ndimage # label, generate_binary_structure, find_objects, binary_dilation

# Gráficos e widgets:
import plotly.graph_objects as go
from ipywidgets import widgets

In [2]:
def step_baseline(ini_cnt_mplet, fin_cnt_mplet, multiplet_counts):
    """Calculate step baseline inside a region. Called just by calculate_base_line."""
    _y0 = ini_cnt_mplet
    _y1 = fin_cnt_mplet
    _ys = multiplet_counts
    contin = np.zeros(_ys.size)
    gross_area = np.sum(_ys)+_y1
    delta_y = _y1-_y0
    n_ys = _ys.size
    print(gross_area)
    print('===')
    for i in range(n_ys):
        print(i)
        sum_y = np.sum(_ys[0:i+1])
        print(sum_y)
        result = _y0 + delta_y * sum_y/gross_area
        print(result)
        contin[i] = result
        print(contin[i])
        print('===')
    return contin

In [3]:
rng = np.random.default_rng(seed=42)
print(rng)

arr1 = rng.random((3, 3))

arr1

Generator(PCG64)


array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])

In [4]:
rng2 = np.random.default_rng(seed=42).normal(50,13,24)
print(rng2)

[53.96132204 36.48020662 59.75586555 62.22734131 24.63654255 33.07166641
 51.66192524 45.8888463  49.78158495 38.91042894 61.43217367 60.11129516
 50.85839907 64.65413569 56.07762145 38.82919798 54.79376019 37.53452619
 61.41985392 49.35096316 47.59678927 41.14791592 65.8930374  47.99111673]


In [5]:
rng3 = np.random.default_rng(seed=42).normal(50,13)
print(rng3)

53.96132203680761


In [6]:
xs = np.linspace(-5, 5, num=201)
ys = sta.norm.pdf(xs, loc=2.2, scale=0.5)
ys_noise = np.random.default_rng().normal(ys,np.sqrt(ys))

In [7]:
ys

array([7.48666116e-46, 3.14413192e-45, 1.30728536e-44, 5.38142247e-44,
       2.19321312e-43, 8.84955917e-43, 3.53524482e-42, 1.39821645e-41,
       5.47502838e-41, 2.12253763e-40, 8.14669536e-40, 3.09574093e-39,
       1.16467512e-38, 4.33812480e-38, 1.59976555e-37, 5.84073759e-37,
       2.11123270e-36, 7.55547144e-36, 2.67697360e-35, 9.39039072e-35,
       3.26122147e-34, 1.12133139e-33, 3.81719827e-33, 1.28650807e-32,
       4.29276747e-32, 1.41814053e-31, 4.63829355e-31, 1.50194575e-30,
       4.81512226e-30, 1.52833108e-29, 4.80269080e-29, 1.49420046e-28,
       4.60246142e-28, 1.40355199e-27, 4.23763851e-27, 1.26670756e-26,
       3.74874480e-26, 1.09837957e-25, 3.18622227e-25, 9.15075118e-25,
       2.60192324e-24, 7.32469034e-24, 2.04146112e-23, 5.63313309e-23,
       1.53891973e-22, 4.16235364e-22, 1.11460000e-21, 2.95499099e-21,
       7.75622386e-21, 2.01558708e-20, 5.18572940e-20, 1.32091597e-19,
       3.33117606e-19, 8.31719796e-19, 2.05595471e-18, 5.03161155e-18,
      

In [8]:
fig_tests = go.FigureWidget();
fig_tests.add_trace(
    go.Scatter(x=xs,
               y=ys_noise,
               name='ys_noise',
               line=dict(color='navy',width=0.3),
               mode='markers'));
fig_tests.add_trace(
    go.Scatter(x=xs,
               y=ys,
               name='ys',
               line=dict(color='red',width=0.5)));
# Set title and scale type
fig_tests.update_layout(title_text='fig_tests')
# fig_tests.update_yaxes(type='log');
fig_tests.write_html('fig_tests.html', auto_open=True)

In [9]:
# Quando scale1 / 2.2

In [10]:
1 / (2*np.pi)

0.15915494309189535

In [11]:
step_baseline(15, 12, np.array([13, 57, 94, 62, 16, 14, 9]))

277
===
0
13
14.859205776173285
14.859205776173285
===
1
70
14.24187725631769
14.24187725631769
===
2
164
13.223826714801444
13.223826714801444
===
3
226
12.552346570397113
12.552346570397113
===
4
242
12.379061371841155
12.379061371841155
===
5
256
12.227436823104693
12.227436823104693
===
6
265
12.129963898916968
12.129963898916968
===


array([14.85920578, 14.24187726, 13.22382671, 12.55234657, 12.37906137,
       12.22743682, 12.1299639 ])

In [12]:
step_baseline(15, 10, np.array([10, 10, 10, 100000, 10, 10, 10]))

100070
===
0
10
14.999500349755172
14.999500349755172
===
1
20
14.999000699510344
14.999000699510344
===
2
30
14.998501049265514
14.998501049265514
===
3
100030
10.001998600979315
10.001998600979315
===
4
100040
10.001498950734486
10.001498950734486
===
5
100050
10.000999300489656
10.000999300489656
===
6
100060
10.000499650244828
10.000499650244828
===


array([14.99950035, 14.9990007 , 14.99850105, 10.0019986 , 10.00149895,
       10.0009993 , 10.00049965])

In [13]:
pico = np.array([1, 4, 6, 4, 1])

In [14]:
np.sum(pico[0:5])

16

In [15]:
np.array(pico)

array([1, 4, 6, 4, 1])

In [16]:
pico

array([1, 4, 6, 4, 1])