In [1]:
# 2023-Apr-26
# Jupyter notebook for Piscina IEA-R1 calculation 2022 & 2023.

In [2]:
import numpy as np
from numpy.random import default_rng
from numpy.polynomial import Polynomial as P
import time
# from scipy import special
import scipy as sci
import pandas as pd

from ograyspy_class import select_spectrum_from_folder_list
from spec_class import Spec

In [3]:
import plotly.graph_objects as go
import plotly.express as px

In [4]:
# a spectrum pattern to find and test:

In [5]:
# a_pattern = 'SI11318.Chn'
# a_pattern = 'SI00718.Chn'

In [6]:
from ograyspy_class import Ograyspy

In [7]:
si_2022 = 'Genie_Transfer/Si/SI2022'

In [8]:
ogra = Ograyspy(batch_mode=False, folder_to_find=si_2022)
print('Objeto ogra: Ograyspy criado.')
print(f'ogra.info_plat: {ogra.info_plat}')
print(f'ogra.info_mach: {ogra.info_mach}')
print(f'ogra.info_syst: {ogra.info_syst}')
print(f'ogra.info_node: {ogra.info_node}')
print(f'ogra.home_path: {ogra.home_path}')

Found folder name:  /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022
Partes:  ('/', 'home', 'marcelofm', 'Nextcloud', 'Genie_Transfer', 'Si', 'SI2022')
No. spec files:  49
Objeto ogra: Ograyspy criado.
ogra.info_plat: Linux-5.19.0-41-generic-x86_64-with-glibc2.36
ogra.info_mach: x86_64
ogra.info_syst: Linux
ogra.info_node: marcelofm-X540LA
ogra.home_path: /home/marcelofm


In [9]:
# Select a machine/system to read from:
spectra_list_df = pd.read_pickle(ogra.pkl_folder_files)
spectra_list_df

info_plat info_mach info_syst  \
0  Linux-5.19.0-41-generic-x86_64-with-glibc2.36    x86_64     Linux   

          info_node        home_path  \
0  marcelofm-X540LA  /home/marcelofm   

                                        spectra_path  n_files  a_spec_ind  \
0  /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI...       49           0   

  a_spec_name reduced_f_name  \
0                              

                                          files_list  \
0  [/home/marcelofm/Nextcloud/Genie_Transfer/Si/S...   

                            reduced_names_files_list  \
0  [SI02622.Chn, SI07222.Chn, SI04022 (cont em 31...   

                    spectra_pattern_names           pkl_folder_files  
0  [**/*.[Cc][Hh][Nn], **/*.[Ii][Ee][Cc]]  Linuxmarcelofm-X540LA.pkl

In [10]:
reduc_nms = spectra_list_df.reduced_names_files_list[0]
fil_lst = spectra_list_df.files_list[0]
spc_pth = spectra_list_df.spectra_path[0]

In [11]:
reduc_nms

['SI02622.Chn',
 'SI07222.Chn',
 'SI04022 (cont em 31-05-22).Chn',
 'SI02722.Chn',
 'SI08222.Chn',
 'SI09222.Chn',
 'SI05322.Chn',
 'SI03222.Chn',
 'SI08622.Chn',
 'SI02522.Chn',
 'SI09322.Chn',
 'SI00922.Chn',
 'SI08522.Chn',
 'SI07922.Chn',
 'SI03322.Chn',
 'SI05922.Chn',
 'SI03022.Chn',
 'SI08722.Chn',
 'FRASCO ORIGINAL SI084_22.Chn',
 'SI06122.Chn',
 'SI01822.Chn',
 'SI09422.Chn',
 'SI00822.Chn',
 'SI05822.Chn',
 'SI04722.Chn',
 'SI01622.Chn',
 'SI08422.Chn',
 'SI02022.Chn',
 'SI07522.Chn',
 'SI01722.Chn',
 'SI06922.Chn',
 'SI09722.Chn',
 'SI06522.Chn',
 'SI09122.Chn',
 'SI05522.Chn',
 'SI03422.Chn',
 'SI04422.Chn',
 'SI03722.Chn',
 'SI05622.Chn',
 'SI02922.Chn',
 'SI07722.Chn',
 'SI03522.Chn',
 'SI05122.Chn',
 'SI06722.Chn',
 'SI06322.Chn',
 'SI07322.Chn',
 'SI03122.Chn',
 'SI01922.Chn',
 'BGTESTE.Chn']

In [12]:
a_pattern='SI04722.Chn'

In [13]:
a_spec_name, reduced_f_name = select_spectrum_from_folder_list(reduc_nms, fil_lst, spc_pth, a_pattern)

Existing:
Achou! indice=24, nomearq = SI04722.Chn
name:  /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.Chn
Final choices:
spectra_path: /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022
a_spec_name: /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.Chn
reduced_f_name: SI04722.Chn


In [14]:
a_spec_name, reduced_f_name

(PosixPath('/home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.Chn'),
 'SI04722.Chn')

In [15]:
a_spec = Spec(a_spec_name, reduced_f_name)

In [16]:
vars(a_spec)

{'net_spec_ser_an': None,
 'final_composed_baseline': None,
 'f_name': PosixPath('/home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.Chn'),
 'reduced_f_name': 'SI04722.Chn',
 'sufx': '.chn',
 'spec_io': None,
 'lv_time': 50000.0,
 'rl_time': 50030.1,
 'source_datetime': None,
 'pkl_file': PosixPath('/home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.pkl'),
 'origin_spec_ser_an': <generic_series_analysis_class.GenericSeriesAnalysis at 0x7f0f020c60b0>,
 'start_datetime': datetime.datetime(2022, 6, 20, 17, 34, 1),
 'det_descr': 'MAQUINA_01 MCB 1 Input 1',
 'sam_descr': 'SI047/22 - Agua da piscina do reator IEA- R1 20/06/22 (SI02006)',
 'channel_energy_calib': <genericcalib_class.ChannelEnergyCalib at 0x7f0f020c6f20>}

In [17]:
origin_ser = a_spec.origin_spec_ser_an
ch_en_cal = a_spec.channel_energy_calib

In [18]:
vars(origin_ser)

{'mix_regions': None,
 'spl_baseline': None,
 'eval_baseline': None,
 'y_s': array([0, 0, 0, ..., 8, 2, 4]),
 'nzero': array([False, False, False, ...,  True,  True,  True]),
 'n_ch': 4096,
 'final_baseline': None,
 'x_s': array([0.000e+00, 1.000e+00, 2.000e+00, ..., 4.093e+03, 4.094e+03,
        4.095e+03]),
 'chans_nzero': array([  23.,   24.,   25., ..., 4093., 4094., 4095.]),
 'counts_nzero': array([  1,   8, 159, ...,   8,   2,   4]),
 'unc_y': array([ 1.        ,  2.82842712, 12.60952021, ...,  2.82842712,
         1.41421356,  2.        ]),
 'given_variance': array([0, 0, 0, ..., 8, 2, 4]),
 'y_smoothed': None,
 'fft_s': None,
 'is_reg': array([False, False, False, ..., False, False, False]),
 'xs_all_mplets': [],
 'ys_all_mplets': [],
 'ys_all_steps': [],
 'chans_in_multiplets_list': [],
 'calculated_step_counts': [],
 'xs_bl_in_reg': array([], dtype=float64),
 'ys_bl_in_reg': array([], dtype=float64),
 'xs_bl_out_reg': array([], dtype=float64),
 'ys_bl_out_reg': array([], dtyp

In [19]:
vars(ch_en_cal)

{'calib_kind': 'channel energy',
 'p_en': Polynomial([-1.99049842,  0.61104035,  0.        ], domain=[-1,  1], window=[-1,  1]),
 'coeffs_ch_en': array([ 0.        ,  0.61104035, -1.99049842]),
 'en_ch_calib': array([], dtype=float64),
 'chan_calib': array([], dtype=float64)}

In [20]:
y0_s = np.array(origin_ser.y_s)
y0_s

array([0, 0, 0, ..., 8, 2, 4])

In [21]:
x0_s = np.array(origin_ser.x_s)
x0_s

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 4.093e+03, 4.094e+03,
       4.095e+03])

In [22]:
x_nz = origin_ser.chans_nzero
y_nz = origin_ser.counts_nzero

In [23]:
unc_y = origin_ser.unc_y

In [24]:
y0_s

array([0, 0, 0, ..., 8, 2, 4])

In [25]:
# Seleciona sensibilidade dos picos do espectro de referência:
promin = 30

In [26]:
# pks = sci.signal.find_peaks_cwt(y0_s, widths=(3,15), min_snr=1, noise_perc=10, max_distances=(1,20))
# pks

In [27]:
pks, _ = sci.signal.find_peaks(y0_s, prominence=promin)
pks

array([  26,   39,   44,   50,   53,   61,   70,   80,   87,   89,   95,
        104,  112,  122,  126,  135,  142,  147,  155,  166,  177,  182,
        186,  191,  196,  200,  206,  211,  223,  233,  241,  244,  248,
        250,  257,  265,  274,  281,  289,  292,  297,  299,  309,  315,
        331,  333,  341,  346,  349,  353,  358,  362,  365,  369,  371,
        377,  386,  390,  393,  399,  408,  418,  424,  428,  431,  434,
        437,  441,  447,  452,  456,  458,  466,  470,  478,  480,  486,
        494,  498,  503,  512,  523,  527,  533,  535,  543,  549,  552,
        557,  564,  566,  568,  579,  586,  588,  591,  599,  620,  624,
        631,  641,  647,  652,  665,  670,  674,  678,  686,  690,  696,
        701,  707,  718,  720,  723,  726,  728,  734,  741,  753,  760,
        768,  775,  779,  787,  799,  809,  815,  839,  847,  852,  861,
        865,  871,  883,  896,  900,  908,  926,  930,  939,  947,  957,
        965,  988, 1000, 1009, 1015, 1025, 1050, 10

In [28]:
y0_s_pks = y0_s[pks]
y0_s_pks

array([ 456,  683,  618,  568,  558,  491,  496,  492,  496,  477,  523,
        673,  638, 1045, 1380,  598,  991,  768,  648,  651,  679,  666,
        649,  685,  687,  692,  721,  721,  801,  971,  741,  714,  728,
        750,  696,  706,  681,  695,  692,  651,  695,  688,  750,  628,
        638,  656,  599,  628,  624,  615,  661,  625,  607,  601,  574,
        686,  546,  539,  678,  555,  503,  489,  492,  468,  485,  470,
        480,  456,  477,  455,  453,  471,  453,  452,  463,  413,  474,
        413,  407,  415,  414,  396,  452,  378,  361,  363,  352,  388,
        375,  339,  344,  341,  466,  314,  309,  334,  356,  304,  296,
        303,  287,  283,  292,  312,  264,  273,  275,  261,  270,  266,
        265,  273,  257,  252,  246,  254,  245,  248,  252,  245,  258,
        238,  226,  226,  301,  221,  217,  221,  830,  219,  212,  218,
        204,  200,  202,  201,  203,  202,  208,  198,  203,  188,  326,
        182,  196,  386,  198,  200,  190,  164,  1

In [29]:
indir_sort = np.argsort(y0_s_pks)[-13:]
indir_sort

array([ 33,  42,  17,  28, 174, 128, 221,  29,  16,  13,  14, 217, 211])

In [30]:
y0_s_pks[indir_sort]

array([ 750,  750,  768,  801,  815,  830,  854,  971,  991, 1045, 1380,
       1508, 1695])

In [31]:
pks[indir_sort]

array([ 250,  309,  147,  223, 1330,  839, 2394,  233,  142,  122,  126,
       2184, 1923])

In [32]:
fig2 = go.Figure(data=go.Scattergl(
    x=x_nz,
    y=y_nz,
    mode='markers'
))


In [33]:
fig2.add_trace(
    go.Scattergl(x=x0_s,
                 y=y0_s,
                 error_y=dict(
                     color='orange',width=3.0,
                     type='data', # value of error bar given in data coordinates
                     array=unc_y,
                     visible=True),
                 name="Counts & uncertaintes",
                 line=dict(color='orange',width=0.3)));

In [34]:
fig2.add_trace(
    go.Scattergl(x=pks,
                 y=y0_s[pks],
                 mode="markers",
                 name="peaks",
                 marker=dict(color='cyan',
                             symbol='circle',
                             size=15,
                             opacity=0.4,
                             line=dict(color='green', width=2.0)
                            )
                ));

In [35]:
# Set title and scale type    width=1800,

fig2.update_layout(
    title_text=reduced_f_name,
    height=900,
    margin=dict(l=10, r=10, t=30, b=10),
    paper_bgcolor="LightSteelBlue"
)
fig2.update_yaxes(type="log");
fig2.write_html('fig2.html', auto_open=True)


In [36]:
# Agora, o grande loop para comparar o espectro escolhido
# com todos os outros:

In [37]:
# Fazendo correlação entre cada espectro da pasta com um bem formado entre eles.
# Método 1: correlação direta

In [38]:
t = time.time()
lista_mix = []
i_n = 0
for i_sp, j_sp in zip(fil_lst, reduc_nms):
    a_spec = Spec(i_sp, j_sp)
    strt = a_spec.start_datetime
    y_s = a_spec.origin_spec_ser_an.y_s
    # convo = sci.signal.correlate(y_s,y_s)
    # convo = sci.signal.convolve(counts, counts)
    # convo = sci.signal.fftconvolve(y_s, y_s)
    # convo = sci.signal.fftconvolve(y_s, np.roll(y_s,1500))
    # shifted_y_s = np.roll(y_s,1319)
    convo = sci.signal.correlate(y_s, y0_s)
    max_arg = np.argmax(abs(convo))
    drift = y_s.size-max_arg-1
    cts_tot = np.sum(y_s)
    pks, _ = sci.signal.find_peaks(y_s, prominence=promin)
    n_pks = pks.size
    indir_sort = np.argsort(y_s[pks])[-13:]
    tall_pks = pks[indir_sort]
    # =  np.array(pks[indir_sort])
    print(f'{i_n}: {j_sp}: {max_arg} ->  {drift}  n_pks: {n_pks}  Tot: {cts_tot}  Start {strt}.')
    for rank, pk in enumerate(tall_pks):
        lista_mix.append([i_n, j_sp, max_arg, drift, n_pks, pk, rank, cts_tot, strt])
    i_n += 1
    # af = sci.fft.fft(y_s)
    # bf = sci.fft.fft(shifted_y_s)
    # c = sci.fft.ifft(af * np.conj(bf))
    # time_shift = np.argmax(abs(c))
elapsd = time.time() - t
elapsd



0: SI02622.Chn: 4094 ->  1  n_pks: 20  Tot: 49377  Start 2022-04-19 19:00:10.
1: SI07222.Chn: 4102 ->  -7  n_pks: 214  Tot: 543063  Start 2022-09-06 17:40:39.
2: SI04022 (cont em 31-05-22).Chn: 4097 ->  -2  n_pks: 225  Tot: 568571  Start 2022-06-29 17:18:04.
3: SI02722.Chn: 4094 ->  1  n_pks: 23  Tot: 54990  Start 2022-04-12 10:59:27.
4: SI08222.Chn: 4102 ->  -7  n_pks: 222  Tot: 535351  Start 2022-10-11 18:50:32.
5: SI09222.Chn: 4109 ->  -14  n_pks: 221  Tot: 546724  Start 2022-11-23 20:55:34.
6: SI05322.Chn: 4095 ->  0  n_pks: 215  Tot: 563877  Start 2022-07-04 17:26:03.
7: SI03222.Chn: 4098 ->  -3  n_pks: 208  Tot: 485859  Start 2022-05-04 16:51:26.
8: SI08622.Chn: 4102 ->  -7  n_pks: 209  Tot: 525153  Start 2022-10-26 17:51:35.
9: SI02522.Chn: 4094 ->  1  n_pks: 201  Tot: 469313  Start 2022-04-13 20:26:18.
10: SI09322.Chn: 4110 ->  -15  n_pks: 214  Tot: 556587  Start 2022-11-24 22:02:03.
11: SI00922.Chn: 4095 ->  0  n_pks: 174  Tot: 560599  Start 2022-02-24 09:44:43.
12: SI08522.Ch

0.44910645484924316

In [39]:
lista_mix

[[0,
  'SI02622.Chn',
  4094,
  1,
  20,
  254,
  0,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  839,
  1,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  229,
  2,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  231,
  3,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  277,
  4,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  2184,
  5,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  1079,
  6,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  171,
  7,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  4094,
  1,
  20,
  25,
  8,
  49377,
  datetime.datetime(2022, 4, 19, 19, 0, 10)],
 [0,
  'SI02622.Chn',
  409

In [40]:
dataf_mix = pd.DataFrame(lista_mix,
                         columns=['i_n', 'j_sp', 'max_arg', 'drift', 'n_pks', 'pk',
                                  'rank', 'cts_tot', 'strt'])
dataf_mix

i_n         j_sp  max_arg  drift  n_pks    pk  rank  cts_tot  \
0      0  SI02622.Chn     4094      1     20   254     0    49377   
1      0  SI02622.Chn     4094      1     20   839     1    49377   
2      0  SI02622.Chn     4094      1     20   229     2    49377   
3      0  SI02622.Chn     4094      1     20   231     3    49377   
4      0  SI02622.Chn     4094      1     20   277     4    49377   
..   ...          ...      ...    ...    ...   ...   ...      ...   
620   48  BGTESTE.Chn     4103     -8    153   153     8   410833   
621   48  BGTESTE.Chn     4103     -8    153   129     9   410833   
622   48  BGTESTE.Chn     4103     -8    153  2403    10   410833   
623   48  BGTESTE.Chn     4103     -8    153   149    11   410833   
624   48  BGTESTE.Chn     4103     -8    153   133    12   410833   

                   strt  
0   2022-04-19 19:00:10  
1   2022-04-19 19:00:10  
2   2022-04-19 19:00:10  
3   2022-04-19 19:00:10  
4   2022-04-19 19:00:10  
..                  ...  
620 2022-10-31 11:10:25  
621 2022-10-31 11:10:25  
622 2022-10-31 11:10:25  
623 2022-10-31 11:10:25  
624 2022-10-31 11:10:25  

[625 rows x 9 columns]

In [41]:
# Plotar picos predominantes

In [42]:
spec_by_date = dataf_mix.sort_values(by='strt')
spec_by_date

i_n         j_sp  max_arg  drift  n_pks    pk  rank  cts_tot  \
275   22  SI00822.Chn     4095      0    140   258     1   398225   
282   22  SI00822.Chn     4095      0    140   225     8   398225   
281   22  SI00822.Chn     4095      0    140   231     7   398225   
280   22  SI00822.Chn     4095      0    140   236     6   398225   
279   22  SI00822.Chn     4095      0    140   243     5   398225   
..   ...          ...      ...    ...    ...   ...   ...      ...   
400   31  SI09722.Chn     4110    -15    228  1344     9   563138   
402   31  SI09722.Chn     4110    -15    228  2199    11   563138   
403   31  SI09722.Chn     4110    -15    228  1938    12   563138   
396   31  SI09722.Chn     4110    -15    228  2409     5   563138   
401   31  SI09722.Chn     4110    -15    228   139    10   563138   

                   strt  
275 2022-02-23 19:10:04  
282 2022-02-23 19:10:04  
281 2022-02-23 19:10:04  
280 2022-02-23 19:10:04  
279 2022-02-23 19:10:04  
..                  ...  
400 2022-12-12 18:07:41  
402 2022-12-12 18:07:41  
403 2022-12-12 18:07:41  
396 2022-12-12 18:07:41  
401 2022-12-12 18:07:41  

[625 rows x 9 columns]

In [43]:
# df = px.data.gapminder().query("continent=='Oceania'")
fig = px.line(spec_by_date, x="strt", y=(["tall_1, tall_2"]))
# , color='country')
fig.show()

ValueError: All arguments should have the same length. The length of argument `y` is 1, whereas the length of  previously-processed arguments ['strt'] is 625

In [44]:
fir=lista_mix[5][:]
sec=[i[5][-2] for i in lista_mix]
thr=[i[5][-3] for i in lista_mix]
fot=[i[5][-4] for i in lista_mix]
fif=[i[5][-5] for i in lista_mix]
fig3 = go.Figure(data=go.Scattergl(
    x=[i[7] for i in lista_mix],
    y=[fir, sec, thr, fot, fif],
    mode='lines+markers'
))
fig3.write_html('fig3.html', auto_open=True)

In [45]:
df = px.data.gapminder().query("continent=='Oceania'")
fig = px.line(df, x="year", y="lifeExp", color='country')
fig.show()

In [46]:
df

In [47]:
teste = np.array([1, 5, 2, 18])

In [48]:
teste

In [49]:
# num=21 dá percentis 0%, 5%, 10%, ... 100%
percentis = np.percentile(drifts, np.linspace(0, 100, num=21))
percentis

In [50]:
# Soma de 1 ano de espectros da piscina.

In [51]:
i_n = 0
i_m = 0
ys_tot = np.zeros(y0_s.size)
for i_sp, j_sp in zip(fil_lst, reduc_nms):
    a_spec = Spec(i_sp, j_sp)
    ori_ser = a_spec.origin_spec_ser_an
    y_s = ori_ser.y_s
    convo = sci.signal.correlate(y_s, y0_s)
    max_arg = np.argmax(abs(convo))
    drift = y_s.size-max_arg-1
    cts_tot = np.sum(y_s)
    pks, _ = sci.signal.find_peaks(y_s, prominence=promin)
    n_pks = pks.size
    print(f'{i_n}: {j_sp}: {max_arg} ->  {drift}  n_pks: {n_pks}  Tot: {cts_tot}.')
    if abs(drift) < 60:
        ys_tot += np.roll(y_s, -drift)
        # ys_tot += y_s
        i_m += 1
    i_n += 1
    # af = sci.fft.fft(y_s)
    # bf = sci.fft.fft(shifted_y_s)
    # c = sci.fft.ifft(af * np.conj(bf))
    # time_shift = np.argmax(abs(c))

In [ ]:
i_m

In [ ]:
fig2 = go.Figure(data=go.Scattergl(
    x=x_nz,
    y=y_nz,
    mode='markers'
))


In [ ]:
fig2.add_trace(
    go.Scattergl(x=x0_s,
                 y=ys_tot,
                 error_y=dict(
                     color='orange',width=3.0,
                     type='data', # value of error bar given in data coordinates
                     array=unc_y,
                     visible=True),
                 name="Counts & uncertaintes",
                 line=dict(color='orange',width=0.3)));

In [ ]:
fig2.add_trace(
    go.Scattergl(x=pks,
                 y=y0_s[pks],
                 mode="markers",
                 name="peaks",
                 marker=dict(color='cyan',
                             symbol='circle',
                             size=15,
                             opacity=0.4,
                             line=dict(color='green', width=2.0)
                            )
                ));

In [ ]:
# Set title and scale type    width=1800,

fig2.update_layout(
    title_text="Gamma-ray spectrum excerpt",
    height=900,
    margin=dict(l=10, r=10, t=30, b=10),
    paper_bgcolor="LightSteelBlue"
)
fig2.update_yaxes(type="log");
fig2.write_html('fig2.html', auto_open=True)


In [ ]:
# Das Ende