In [1]:
# 2023-Apr-26
# Jupyter notebook for Piscina IEA-R1 calculation 2022 & 2023.

In [2]:
import numpy as np
from numpy.random import default_rng
from numpy.polynomial import Polynomial as P
import time
# from scipy import special
import scipy as sci
import pandas as pd

from ograyspy_class import select_spectrum_from_folder_list
from spec_class import Spec

In [3]:
import plotly.graph_objects as go

In [4]:
# a spectrum pattern to find and test:

In [5]:
# a_pattern = 'SI11318.Chn'
# a_pattern = 'SI00718.Chn'

In [6]:
from ograyspy_class import Ograyspy

In [7]:
si_2022 = 'Genie_Transfer/Si/SI2022'

In [8]:
ogra = Ograyspy(batch_mode=False, folder_to_find=si_2022)
print('Objeto ogra: Ograyspy criado.')
print(f'ogra.info_plat: {ogra.info_plat}')
print(f'ogra.info_mach: {ogra.info_mach}')
print(f'ogra.info_syst: {ogra.info_syst}')
print(f'ogra.info_node: {ogra.info_node}')
print(f'ogra.home_path: {ogra.home_path}')

Found folder name:  /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022
Partes:  ('/', 'home', 'marcelofm', 'Nextcloud', 'Genie_Transfer', 'Si', 'SI2022')
No. spec files:  49
Objeto ogra: Ograyspy criado.
ogra.info_plat: Linux-6.2.0-20-generic-x86_64-with-glibc2.37
ogra.info_mach: x86_64
ogra.info_syst: Linux
ogra.info_node: mmaduar-net13
ogra.home_path: /home/marcelofm


In [9]:
# Select a machine/system to read from:
spectra_list_df = pd.read_pickle(ogra.pkl_folder_files)
spectra_list_df

info_plat info_mach info_syst  \
0  Linux-6.2.0-20-generic-x86_64-with-glibc2.37    x86_64     Linux   

       info_node        home_path  \
0  mmaduar-net13  /home/marcelofm   

                                        spectra_path  n_files  a_spec_ind  \
0  /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI...       49           0   

  a_spec_name reduced_f_name  \
0                              

                                          files_list  \
0  [/home/marcelofm/Nextcloud/Genie_Transfer/Si/S...   

                            reduced_names_files_list  \
0  [SI07222.Chn, SI01922.Chn, SI05622.Chn, SI0922...   

                    spectra_pattern_names        pkl_folder_files  
0  [**/*.[Cc][Hh][Nn], **/*.[Ii][Ee][Cc]]  Linuxmmaduar-net13.pkl

In [10]:
reduc_nms = spectra_list_df.reduced_names_files_list[0]
fil_lst = spectra_list_df.files_list[0]
spc_pth = spectra_list_df.spectra_path[0]

In [11]:
reduc_nms

['SI07222.Chn',
 'SI01922.Chn',
 'SI05622.Chn',
 'SI09222.Chn',
 'SI06922.Chn',
 'SI09422.Chn',
 'SI03422.Chn',
 'SI03222.Chn',
 'SI08422.Chn',
 'SI05522.Chn',
 'SI02522.Chn',
 'SI05322.Chn',
 'SI04722.Chn',
 'SI07722.Chn',
 'SI06122.Chn',
 'SI05922.Chn',
 'SI07922.Chn',
 'SI09322.Chn',
 'SI08722.Chn',
 'SI00822.Chn',
 'SI01722.Chn',
 'SI03322.Chn',
 'SI03122.Chn',
 'SI08222.Chn',
 'SI02722.Chn',
 'SI02622.Chn',
 'FRASCO ORIGINAL SI084_22.Chn',
 'SI04022 (cont em 31-05-22).Chn',
 'SI06322.Chn',
 'SI09722.Chn',
 'SI01822.Chn',
 'SI06722.Chn',
 'SI07522.Chn',
 'SI03022.Chn',
 'SI03722.Chn',
 'SI02022.Chn',
 'SI05822.Chn',
 'SI04422.Chn',
 'BGTESTE.Chn',
 'SI01622.Chn',
 'SI09122.Chn',
 'SI07322.Chn',
 'SI03522.Chn',
 'SI02922.Chn',
 'SI05122.Chn',
 'SI06522.Chn',
 'SI00922.Chn',
 'SI08522.Chn',
 'SI08622.Chn']

In [12]:
a_pattern='SI04722.Chn'

In [13]:
a_spec_name, reduced_f_name = select_spectrum_from_folder_list(reduc_nms, fil_lst, spc_pth, a_pattern)

Existing:
Achou! indice=12, nomearq = SI04722.Chn
name:  /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.Chn
Final choices:
spectra_path: /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022
a_spec_name: /home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.Chn
reduced_f_name: SI04722.Chn


In [14]:
a_spec_name, reduced_f_name

(PosixPath('/home/marcelofm/Nextcloud/Genie_Transfer/Si/SI2022/SI04722.Chn'),
 'SI04722.Chn')

In [15]:
a_spec = Spec(a_spec_name, reduced_f_name)

In [16]:
y0_s = np.array(a_spec.gross_spec_ser_an.y_s)
y0_s

array([0, 0, 0, ..., 8, 2, 4])

In [17]:
x0_s = np.array(a_spec.gross_spec_ser_an.x_s)
x0_s

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 4.093e+03, 4.094e+03,
       4.095e+03])

In [18]:
gross_ser = a_spec.gross_spec_ser_an

In [19]:
x_nz = gross_ser.chans_nzero
y_nz = gross_ser.counts_nzero

In [20]:
unc_y = gross_ser.unc_y

In [21]:
y0_s

array([0, 0, 0, ..., 8, 2, 4])

In [36]:
# Seleciona sensibilidade dos picos do espectro de referência:
promin = 30

In [37]:
# pks = sci.signal.find_peaks_cwt(y0_s, widths=(3,15), min_snr=1, noise_perc=10, max_distances=(1,20))
# pks

In [38]:
pks, _ = sci.signal.find_peaks(y0_s, prominence=promin)
pks

array([  26,   39,   44,   50,   53,   61,   70,   80,   87,   89,   95,
        104,  112,  122,  126,  135,  142,  147,  155,  166,  177,  182,
        186,  191,  196,  200,  206,  211,  223,  233,  241,  244,  248,
        250,  257,  265,  274,  281,  289,  292,  297,  299,  309,  315,
        331,  333,  341,  346,  349,  353,  358,  362,  365,  369,  371,
        377,  386,  390,  393,  399,  408,  418,  424,  428,  431,  434,
        437,  441,  447,  452,  456,  458,  466,  470,  478,  480,  486,
        494,  498,  503,  512,  523,  527,  533,  535,  543,  549,  552,
        557,  564,  566,  568,  579,  586,  588,  591,  599,  620,  624,
        631,  641,  647,  652,  665,  670,  674,  678,  686,  690,  696,
        701,  707,  718,  720,  723,  726,  728,  734,  741,  753,  760,
        768,  775,  779,  787,  799,  809,  815,  839,  847,  852,  861,
        865,  871,  883,  896,  900,  908,  926,  930,  939,  947,  957,
        965,  988, 1000, 1009, 1015, 1025, 1050, 10

In [39]:
y0_s_pks = y0_s[pks]
y0_s_pks

array([ 456,  683,  618,  568,  558,  491,  496,  492,  496,  477,  523,
        673,  638, 1045, 1380,  598,  991,  768,  648,  651,  679,  666,
        649,  685,  687,  692,  721,  721,  801,  971,  741,  714,  728,
        750,  696,  706,  681,  695,  692,  651,  695,  688,  750,  628,
        638,  656,  599,  628,  624,  615,  661,  625,  607,  601,  574,
        686,  546,  539,  678,  555,  503,  489,  492,  468,  485,  470,
        480,  456,  477,  455,  453,  471,  453,  452,  463,  413,  474,
        413,  407,  415,  414,  396,  452,  378,  361,  363,  352,  388,
        375,  339,  344,  341,  466,  314,  309,  334,  356,  304,  296,
        303,  287,  283,  292,  312,  264,  273,  275,  261,  270,  266,
        265,  273,  257,  252,  246,  254,  245,  248,  252,  245,  258,
        238,  226,  226,  301,  221,  217,  221,  830,  219,  212,  218,
        204,  200,  202,  201,  203,  202,  208,  198,  203,  188,  326,
        182,  196,  386,  198,  200,  190,  164,  1

In [40]:
indir_sort = np.argsort(y0_s_pks)[-13:]
indir_sort

array([ 33,  42,  17,  28, 174, 128, 221,  29,  16,  13,  14, 217, 211])

In [41]:
y0_s_pks[indir_sort]

array([ 750,  750,  768,  801,  815,  830,  854,  971,  991, 1045, 1380,
       1508, 1695])

In [42]:
pks[indir_sort]

array([ 250,  309,  147,  223, 1330,  839, 2394,  233,  142,  122,  126,
       2184, 1923])

In [29]:
fig2 = go.Figure(data=go.Scattergl(
    x=x_nz,
    y=y_nz,
    mode='markers'
))


In [30]:
fig2.add_trace(
    go.Scattergl(x=x0_s,
                 y=y0_s,
                 error_y=dict(
                     color='orange',width=3.0,
                     type='data', # value of error bar given in data coordinates
                     array=unc_y,
                     visible=True),
                 name="Counts & uncertaintes",
                 line=dict(color='orange',width=0.3)));

In [31]:
fig2.add_trace(
    go.Scattergl(x=pks,
                 y=y0_s[pks],
                 mode="markers",
                 name="peaks",
                 marker=dict(color='cyan',
                             symbol='circle',
                             size=15,
                             opacity=0.4,
                             line=dict(color='green', width=2.0)
                            )
                ));

In [32]:
# Set title and scale type    width=1800,

fig2.update_layout(
    title_text=reduced_f_name,
    height=900,
    margin=dict(l=10, r=10, t=30, b=10),
    paper_bgcolor="LightSteelBlue"
)
fig2.update_yaxes(type="log");
fig2.write_html('fig2.html', auto_open=True)


In [33]:
# Agora, o grande loop para comparar o espectro escolhido
# com todos os outros:

In [34]:
# Fazendo correlação entre cada espectro da pasta com um bem formado entre eles.
# Método 1: correlação direta

In [35]:
recorte = slice(1700, 4000)

In [ ]:
t = time.time()
# do stuff

In [ ]:
i_n = 0
lista_mix = []
for i_sp, j_sp in zip(fil_lst, reduc_nms):
    a_spec = Spec(i_sp, j_sp)
    gross_ser = a_spec.gross_spec_ser_an
    y_s = gross_ser.y_s
    # convo = sci.signal.correlate(y_s,y_s)
    # convo = sci.signal.convolve(counts, counts)
    # convo = sci.signal.fftconvolve(y_s, y_s)
    # convo = sci.signal.fftconvolve(y_s, np.roll(y_s,1500))
    # shifted_y_s = np.roll(y_s,1319)
    convo = sci.signal.correlate(y_s[recorte], y0_s[recorte])
    max_arg = np.argmax(abs(convo))
    drift = y_s.size-max_arg-1-1796
    cts_tot = np.sum(y_s)
    pks, _ = sci.signal.find_peaks(y_s, prominence=promin)
    n_pks = pks.size
    print(f'{i_n}: {j_sp}: {max_arg} ->  {drift}  n_pks: {n_pks}  Tot: {cts_tot}.')
    lista_mix.append([i_n, j_sp, max_arg, drift, n_pks, cts_tot])
    i_n += 1
    # af = sci.fft.fft(y_s)
    # bf = sci.fft.fft(shifted_y_s)
    # c = sci.fft.ifft(af * np.conj(bf))
    # time_shift = np.argmax(abs(c))

In [ ]:
elapsd = time.time() - t
elapsd

In [ ]:
drifts = np.array([l[3] for l in lista_mix])
drifts

In [ ]:
# num=21 dá percentis 0%, 5%, 10%, ... 100%
percentis = np.percentile(drifts, np.linspace(0, 100, num=21))
percentis

In [ ]:
# Soma de 1 ano de espectros da piscina.

In [ ]:
i_n = 0
i_m = 0
ys_tot = np.zeros(y0_s.size)
for i_sp, j_sp in zip(fil_lst, reduc_nms):
    a_spec = Spec(i_sp, j_sp)
    gross_ser = a_spec.gross_spec_ser_an
    y_s = gross_ser.y_s
    convo = sci.signal.correlate(y_s[recorte], y0_s[recorte])
    max_arg = np.argmax(abs(convo))
    drift = y_s.size-max_arg-1-1796
    cts_tot = np.sum(y_s)
    pks, _ = sci.signal.find_peaks(y_s, prominence=promin)
    n_pks = pks.size
    print(f'{i_n}: {j_sp}: {max_arg} ->  {drift}  n_pks: {n_pks}  Tot: {cts_tot}.')
    if abs(drift) < 60:
        ys_tot += np.roll(y_s, -drift)
        # ys_tot += y_s
        i_m += 1
    i_n += 1
    # af = sci.fft.fft(y_s)
    # bf = sci.fft.fft(shifted_y_s)
    # c = sci.fft.ifft(af * np.conj(bf))
    # time_shift = np.argmax(abs(c))

In [ ]:
i_m

In [ ]:
fig2 = go.Figure(data=go.Scattergl(
    x=x_nz,
    y=y_nz,
    mode='markers'
))


In [ ]:
fig2.add_trace(
    go.Scattergl(x=x0_s,
                 y=ys_tot,
                 error_y=dict(
                     color='orange',width=3.0,
                     type='data', # value of error bar given in data coordinates
                     array=unc_y,
                     visible=True),
                 name="Counts & uncertaintes",
                 line=dict(color='orange',width=0.3)));

In [ ]:
fig2.add_trace(
    go.Scattergl(x=pks,
                 y=y0_s[pks],
                 mode="markers",
                 name="peaks",
                 marker=dict(color='cyan',
                             symbol='circle',
                             size=15,
                             opacity=0.4,
                             line=dict(color='green', width=2.0)
                            )
                ));

In [ ]:
# Set title and scale type    width=1800,

fig2.update_layout(
    title_text="Gamma-ray spectrum excerpt",
    height=900,
    margin=dict(l=10, r=10, t=30, b=10),
    paper_bgcolor="LightSteelBlue"
)
fig2.update_yaxes(type="log");
fig2.write_html('fig2.html', auto_open=True)


In [ ]:
# Das Ende