In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 22 10:40:56 2020

@author: marcelo

ar1:
- array (nx,2), onde:
    nx: n'umero total de picos em todas as escalas
    x: 'indice do pico
    ar1[x,0]: canal inteiro do pico
    ar1[x,1]: valor da escala
    
xpk:
- lista (nx), onde:
    nx: numero de picos efetivos ap'os an'alise
    x: canal inteiro do pico
    
ypk:
- lista (nx), onde:
    nx: numero de picos efetivos ap'os an'alise (= nx(xpk))
    x: valor da escala

"""

import numpy as np

from spectrum_analysis import (cwt_complete_analysis, cwt_calc_peaks)
from teste_datas import (Spec)

from machine_selection import set_screen_size_by_machine
from bokeh.plotting import figure, output_file, output_notebook, show
from bokeh.layouts import gridplot

from bokeh import palettes

fn2 = '../gamma/spectra/ALMERA-2017-3/ALM-17-3-#5_PreliA.IEC'

spec2 = Spec()
if spec2.readSp( fn2 ) >= 0:
    print (spec2.spLngData)
    
counts = spec2.spCounts
print(len(counts))

ret = cwt_complete_analysis(counts)

(xs, y0s, ar1, lblimag1, num_feat_imag1, ridges, xpks, ypks,
 ind_ypks, retang_indicess, peaks_masks, cwtpks, nscpks) = ret

8192
8192


In [2]:
(nscpk_ma, cwtpk_ma, pospk_ma) = peaks_masks
valid_peaks = ~(cwtpk_ma.mask | nscpk_ma.mask | ~pospk_ma)

In [3]:
default_plot_width, default_plot_height = set_screen_size_by_machine()

# Bokeh graph w/ peaks in all scales
bokridges1 = figure(
   plot_width =default_plot_width,
   plot_height=int(default_plot_height*0.5),
   tools="pan,box_zoom,reset,save",
   # x_axis_label='channels',
   y_axis_label='scale'
)
bokridges1.circle(ar1[:,0], ar1[:,1], legend_label="cwt peaks", color="navy",size=2)
bokridges1.circle(xpks[valid_peaks], ypks[valid_peaks], color="red",size=8)
bokridges1.circle(xpks[nscpk_ma.mask], ypks[nscpk_ma.mask], color="orange",size=8)
bokridges1.circle(xpks[cwtpk_ma.mask], ypks[cwtpk_ma.mask], color="green",size=6)
bokridges1.circle(xpks[~pospk_ma], ypks[~pospk_ma], color="cyan",size=4)
bokridges2 = figure(
   plot_width =default_plot_width,
   plot_height=int(default_plot_height*0.5),
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", y_range=[1.0e1, 1.0e5],
   x_axis_label='channels', y_axis_label='counts'
)
bokridges2.line(xs, y0s, color="green")
# https://docs.bokeh.org/en/latest/docs/reference/layouts.html
p = gridplot([bokridges1, bokridges2], ncols=1)
show(p)

In [4]:
valid_xpks = np.asarray(xpks)[valid_peaks]
valid_xpks

array([ 237,  271,  380,  392,  442,  456,  694,  718,  728,  827,  921,
        944,  994, 1008, 1209, 1226, 1496, 1783, 1958, 2055, 2303, 2340,
       2380, 2402, 2433, 2467, 2586, 2675, 2703, 2938, 2954, 3086, 3370,
       3561, 3646, 3684, 3892, 3981, 4083, 4250, 4615, 4732, 4884, 4909,
       5330, 5676, 5853, 5991, 6120, 6274, 6491, 6981, 7102, 7135, 7648,
       7797, 7821, 8024, 8080, 2077, 8106,  844, 4356])

In [5]:
valid_ypks = np.asarray(ypks)[valid_peaks]
valid_ypks

array([ 3.76130612,  3.76130612,  2.58710204,  3.17420408,  4.05485714,
        3.4677551 ,  3.17420408,  2.88065306,  2.58710204,  3.4677551 ,
        3.17420408,  4.34840816,  3.4677551 ,  2.58710204,  3.76130612,
        4.64195918,  4.9355102 ,  5.52261224,  2.88065306,  4.9355102 ,
        8.16457143,  8.45812245,  5.52261224,  3.76130612,  6.10971429,
        6.99036735, 12.27428571,  2.88065306,  6.10971429,  4.05485714,
        4.9355102 ,  6.40326531,  6.69681633,  7.87102041,  9.04522449,
        4.9355102 ,  7.57746939,  8.16457143,  7.28391837,  8.16457143,
        7.87102041,  8.16457143,  6.40326531,  5.52261224,  8.75167347,
        8.75167347,  9.63232653,  8.16457143,  7.57746939,  9.33877551,
        9.33877551,  9.63232653,  7.57746939,  8.75167347, 10.21942857,
        6.99036735,  6.69681633,  8.75167347,  7.57746939,  3.17420408,
        7.87102041,  4.64195918,  7.87102041])

In [6]:
valid_cwtpks = np.asarray(cwtpks)[valid_peaks]
valid_cwtpks

array([4.63642518e+03, 3.22518382e+03, 1.79388738e+04, 3.37817389e+04,
       1.00641615e+04, 3.55885662e+03, 4.80476259e+01, 6.18105240e+01,
       5.47266310e+01, 7.19101178e+01, 7.12169226e+01, 8.55183114e+03,
       1.55438993e+02, 1.10263799e+02, 1.50248181e+03, 1.31314159e+04,
       2.71672602e+04, 4.28764536e+04, 1.86425072e+02, 1.31081750e+02,
       2.26142313e+02, 1.99880706e+02, 1.03685870e+02, 7.82539136e+01,
       2.62728014e+02, 3.10286659e+02, 4.20806810e+02, 3.64439002e+01,
       1.67949780e+02, 1.75384514e+02, 3.10886681e+02, 2.68424403e+04,
       7.50507670e+02, 1.98242374e+02, 1.88262553e+02, 6.53408317e+01,
       2.15365155e+03, 4.95737799e+02, 5.26745890e+02, 2.56422340e+02,
       1.57575958e+02, 1.10667316e+03, 1.32832265e+02, 8.74973610e+01,
       9.33107086e+01, 4.42874435e+03, 4.80324859e+02, 6.62868129e+01,
       1.08269182e+02, 1.52598796e+03, 3.66446595e+02, 9.97007013e+02,
       3.06786975e+02, 5.31786487e+02, 4.37915796e+02, 6.59717015e+01,
      

In [7]:
xs

array([0.000e+00, 1.000e+00, 2.000e+00, ..., 8.189e+03, 8.190e+03,
       8.191e+03])

In [8]:
y0s

array([ 0,  0,  0, ..., 19, 28, 23])

In [9]:
step2 = cwt_calc_peaks(valid_xpks, valid_ypks, valid_cwtpks, xs, y0s)

In [10]:
xpks[pospk_ma]


array([ 237,  271,  380,  392,  442,  456,  694,  718,  728,  827,  921,
        944,  994, 1008, 1209, 1226, 1496, 1783, 1958, 2055, 2303, 2340,
       2380, 2402, 2433, 2467, 2586, 2675, 2703, 2938, 2954, 3086, 3370,
       3561, 3646, 3684, 3892, 3981, 4083, 4250, 4507, 4615, 4732, 4884,
       4909, 4941, 5090, 5118, 5167, 5205, 5330, 5470, 5676, 5853, 5991,
       6120, 6274, 6491, 6524, 6644, 6981, 7102, 7135, 7360, 7401, 7454,
       7648, 7742, 7797, 7821, 8024, 8080, 2077, 4477, 6742, 8106, 5151,
       6606, 7506,  844, 4356])

In [11]:
(azes, bezes, centrpk, ypkregs, fwhms, gau_areas, peak_constructed_spectrum,
           baseline_spectrum, bl_median_smoother) = step2

In [12]:
azes

[array([232., 233., 234., 235., 236., 237., 238., 239., 240., 241., 242.]),
 array([266., 267., 268., 269., 270., 271., 272., 273., 274., 275., 276.]),
 array([375., 376., 377., 378., 379., 380., 381., 382., 383., 384., 385.]),
 array([387., 388., 389., 390., 391., 392., 393., 394., 395., 396., 397.]),
 array([437., 438., 439., 440., 441., 442., 443., 444., 445., 446., 447.]),
 array([451., 452., 453., 454., 455., 456., 457., 458., 459., 460., 461.]),
 array([689., 690., 691., 692., 693., 694., 695., 696., 697., 698., 699.]),
 array([713., 714., 715., 716., 717., 718., 719., 720., 721., 722., 723.]),
 array([723., 724., 725., 726., 727., 728., 729., 730., 731., 732., 733.]),
 array([822., 823., 824., 825., 826., 827., 828., 829., 830., 831., 832.]),
 array([916., 917., 918., 919., 920., 921., 922., 923., 924., 925., 926.]),
 array([939., 940., 941., 942., 943., 944., 945., 946., 947., 948., 949.]),
 array([989., 990., 991., 992., 993., 994., 995., 996., 997., 998., 999.]),
 array([1003

In [13]:
len(azes)

63

In [14]:
bezes

[array([   0. ,  397.9, 1122.8, 2292.7, 2971.6, 2885.5, 2076.4, 1000.3,
         338.2,   62.1,    0. ]),
 array([   0. ,  352.7, 1013.4, 1768.1, 2124.8, 1902.5, 1252.2,  621.9,
         208.6,   41.3,    0. ]),
 array([    0. ,  1645.1,  4837.2,  9236.3, 12667.4, 12562.5,  9312.6,
         4682.7,  1666.8,   197.9,     0. ]),
 array([    0. ,  4339.6, 11842.2, 18828.8, 22875.4, 19803. , 12788.6,
         5745.2,  1861.8,   304.4,     0. ]),
 array([   0. ,  867.5, 2069. , 3437.5, 4933. , 5712.5, 5460. , 4210.5,
        2384. ,  975.5,    0. ]),
 array([   0. ,  407.6, 1212.2, 1717.8, 2215.4, 2317. , 1864.6, 1200.2,
         586.8,  197.4,    0. ]),
 array([  0. , -66.1, -53.2,   9.7, -49.4,   5.5, -35.6,  -4.7, -61.8,
        -94.9,   0. ]),
 array([  0. , -20.7,  36.6,   9.9,  66.2,  50.5,  51.8,  56.1,  52.4,
         53.7,   0. ]),
 array([  0. ,  21.8,  46.6,  64.4,  39.2,  74. ,  -4.2,  41.6,   3.4,
        -32.8,   0. ]),
 array([  0. , -35.1,  41.8,  25.7,  36.6,  52.5,  33.4, 

In [15]:
centrpk

[236.45411675223426,
 270.26498303807017,
 379.5113055264617,
 391.1631584831638,
 442.11481056257173,
 455.6498848024576,
 694.4450784593438,
 719.1865357643758,
 726.2795275590552,
 828.2733944954128,
 916.9661016949151,
 943.4590750417381,
 991.94,
 1005.1839464882942,
 1208.7065745438845,
 1225.7158766071016,
 1495.2827752888472,
 1782.3245464457777,
 1958.681141439206,
 2054.981083404987,
 2303.100826446281,
 2339.2260638297876,
 2379.253561253561,
 2400.523719165086,
 2433.3503184713372,
 2466.2927024859664,
 2585.458612975392,
 2675.012578616352,
 2702.690298507462,
 2937.9006211180126,
 2953.4327044025167,
 3085.737287779988,
 3369.9050669772855,
 3560.7388059701498,
 3646.501547987616,
 3684.128,
 3891.7822736030835,
 3980.5497953615272,
 4082.7730279898224,
 4249.591346153846,
 4614.908183632733,
 4731.885038503851,
 4884.296610169492,
 4908.517730496454,
 5331.082191780822,
 5675.764455911368,
 5853.033898305085,
 5985.76923076923,
 6119.6377551020405,
 6273.531081742537,
 6

In [16]:
#azes, bezes, centrpk, ypkregs, fwhms, gau_areas, peak_constructed_spectrum,
#           baseline_spectrum, bl_median_smoother) = step2

In [17]:
y0s[232:243]

array([1026, 1407, 2115, 3268, 3930, 3827, 3001, 1908, 1229,  936,  857])

In [18]:
xs[232:243]

array([232., 233., 234., 235., 236., 237., 238., 239., 240., 241., 242.])

In [19]:
bezes[0]

array([   0. ,  397.9, 1122.8, 2292.7, 2971.6, 2885.5, 2076.4, 1000.3,
        338.2,   62.1,    0. ])

In [20]:
gau_areas

[13628.327617830502,
 9480.11885385221,
 43731.2532273757,
 91219.85821300902,
 30715.34142348274,
 10044.415508430797,
 129.74162275352117,
 159.0002737543125,
 133.41217413353084,
 202.95706744808726,
 192.3050083073056,
 27028.02034182289,
 438.70658439954934,
 268.80027049806887,
 4416.40134033403,
 42879.74402629698,
 91474.87795018457,
 152714.79075784728,
 479.55648332183716,
 441.36533992040177,
 979.3512816963357,
 881.0444679959929,
 369.3021384620348,
 230.01988179545813,
 984.2531251771571,
 1243.3776915142093,
 2234.451036508623,
 93.74762968240854,
 629.1871728164263,
 535.2651792257028,
 1046.7864998879943,
 102946.76698884787,
 2943.603414242873,
 842.9503160775274,
 858.1507540776555,
 220.00910503632943,
 8985.194900740384,
 2146.8845924033844,
 2154.6347484087783,
 1110.484560821338,
 670.0318443269985,
 4792.653644004813,
 509.4414704329429,
 311.6428729913487,
 418.37623682773165,
 19857.114160543584,
 2259.387028296732,
 287.067352461185,
 451.7071010578977,
 7067

In [21]:
# 2020-02-24
# Tudo em progresso! Agora:
# - Fazer os gr'aficos
# - fazer em v'arias passadas o c'alculo at'e n~ao haver picos na linha-base.

In [24]:
# Bokeh graph w/ peaks in all scales
bokpksallscl = figure(
   plot_width =default_plot_width,
   plot_height=default_plot_height,
   tools="pan,box_zoom,reset,save",
    y_axis_type="log",
    y_range=[10**1, 10**5], title="real spec",
   # y_range=[-1000.0, 1000.0], title="synth",
   x_axis_label='channels', y_axis_label='counts'
)
# bokpksallscl.circle(ar1[:,0], ar1[:,1], legend_label="cwt peaks", color="navy",size=2)
bokpksallscl.line(xs, y0s, color="green")
bokpksallscl.line(xs, peak_constructed_spectrum, color="red")
bokpksallscl.line(xs, bl_median_smoother, color="cyan")
bokpksallscl.line(xs, peak_constructed_spectrum+bl_median_smoother, color="blue")

# bokpksallscl.cross(pk_per_scal[ 0], y0s[pk_per_scal[ 0]]*1.01, color="red",size=2)
show(bokpksallscl)

In [23]:
# Bokeh graph w/ peaks in all scales
bok2 = figure(
   plot_width =default_plot_width,
   plot_height=default_plot_height,
   tools="pan,box_zoom,reset,save",
   # y_axis_type="log",
   # y_range=[10**1, 10**5], title="real spec",
   # y_range=[-1000.0, 1000.0], title="synth",
   x_axis_label='channels', y_axis_label='counts'
)
# bokpksallscl.circle(ar1[:,0], ar1[:,1], legend_label="cwt peaks", color="navy",size=2)
# bokpksallscl.line(xs, y0s, color="green")
bok2.line(xs, peak_constructed_spectrum, color="red")
# bokpksallscl.line(xs, bl_median_smoother, color="cyan")
# bokpksallscl.line(xs, peak_constructed_spectrum+bl_median_smoother, color="blue")

# bokpksallscl.cross(pk_per_scal[ 0], y0s[pk_per_scal[ 0]]*1.01, color="red",size=2)
show(bok2)

In [ ]:
# 2020-02-25 Segunda passada

In [25]:
ret2 = cwt_complete_analysis(bl_median_smoother)

(xs, y0s, ar1, lblimag1, num_feat_imag1, ridges, xpks, ypks,
 ind_ypks, retang_indicess, peaks_masks, cwtpks, nscpks) = ret2

In [26]:
(nscpk_ma, cwtpk_ma, pospk_ma) = peaks_masks
valid_peaks = ~(cwtpk_ma.mask | nscpk_ma.mask | ~pospk_ma)

In [27]:
default_plot_width, default_plot_height = set_screen_size_by_machine()

# Bokeh graph w/ peaks in all scales
bokridges1 = figure(
   plot_width =default_plot_width,
   plot_height=int(default_plot_height*0.5),
   tools="pan,box_zoom,reset,save",
   # x_axis_label='channels',
   y_axis_label='scale'
)
bokridges1.circle(ar1[:,0], ar1[:,1], legend_label="cwt peaks", color="navy",size=2)
bokridges1.circle(xpks[valid_peaks], ypks[valid_peaks], color="red",size=8)
bokridges1.circle(xpks[nscpk_ma.mask], ypks[nscpk_ma.mask], color="orange",size=8)
bokridges1.circle(xpks[cwtpk_ma.mask], ypks[cwtpk_ma.mask], color="green",size=6)
bokridges1.circle(xpks[~pospk_ma], ypks[~pospk_ma], color="cyan",size=4)
bokridges2 = figure(
   plot_width =default_plot_width,
   plot_height=int(default_plot_height*0.5),
   tools="pan,box_zoom,reset,save",
   y_axis_type="log", y_range=[1.0e1, 1.0e5],
   x_axis_label='channels', y_axis_label='counts'
)
bokridges2.line(xs, y0s, color="green")
# https://docs.bokeh.org/en/latest/docs/reference/layouts.html
p = gridplot([bokridges1, bokridges2], ncols=1)
show(p)